### ISSUE TITLE
Impossible level of usability of group folder, as soon as Advanced Permissions are involved

### ISSUE THREAD

**Issue by chlarsen** [nextcloud/groupfolders#1060]
Dear All,
Group folders are great, and permissions are easy, because they are utterly logical. Alas, ever so often, the group folder module seems to defy my initial statement. This seems to be an old and long-standing issue, because the usability of this module, namely its advanced permissions feature, has been creating issues intermittently.
Here is the latest:
I upgraded to the latest version of Nextcloud, including modules. All is fine, and the PHP 7.4 jail is ticking along w8th FreeBSD, PostgreSQL and Redis behind a reverse Nginx cache.
I already had a shared folder used by a single group, with read and write permissions.
After the above upgrade, the use case changed slightly: I needed a folder inside the group folder to be accessible to two members of the group., only, including the group manager. Easy, I thought, using advanced permissions.
As soon as I added the group manager to the advanced permission box in the group folder settings, the group manager could NOT access the sub-folder anymore. OUCH!  I guess this is quite exactly the OPPOSITE of what it is supposed to do. In fact, any mentioning of any user or even the entire group in the advanced permission field blocks the respective folder from sight. 
This renders the entire group folder concept useless, and should be considered a critical bug.
Kindly help, as this is a complete showstopper. Thank you!
Chris

**Comment by Daksol** [comment]
Not arguing with you in that some aspects of Group Folders is not easy. Documentation does not explain things very well IMHO.

Example below of how I configured a set of folders - it seems to be working without problems, This won't be your situation precisely but this can be generalised. 

From what I can see the Advanced Permissions will only grant rights to a subfolder which are a subset of permissions in the parent folder. So:-
*  if GroupX does not have (say) Read+Write on the parent folder you cannot use Advanced Permissions to give GroupX Read+Wriete on the subfolder. 
* Advanced permissions can only be set for individuals who are members of a Group which has rights on the parent folder.

Requirement
* We have two groups of account UsersGroup and ManagersGroup
* We have files relevant to ten different Locations
* There should be a top level folder with read/write for the UsersGroup and ManagersGroup
* Below that there should be ten subfolders, one for each Location
* There is one assigned user for each Location.
* Permissions on each location subfolder
   * The assigned user should have full read-write to their subfolder
   * But the users cannot see any of the other subfolders.
   * There is a group of managers who have full read-write to it all.
* The Managers group can change which user account is allocated to each subfolder.

---
Implemented using GroupFolders with Advanced Permissions like this

* Create Top level folder with Group Folders via https://<SOMEHOSTNAME>/index.php/settings/admin/groupfolders
   * Permissions:- UsersGroup and ManagersGroup both have Write and Delete 
   * Advanced permissions:- Tick box ticked, with ManagersGroup has advanced permissions
   * See screenshot below
   
* Permissions set via the regular web interface for each subfolder
   * This can be done by members of ManagersGroup
   * Create subfolder for each Location and set up permissions
      * Set folder permissions for that subfolder with two sets of permissions as follows:-
      * To enter each of these permissions start by clicking "Add Advanced Permissions Rule"
      * First line is set for UsersGroup, with value DENY against all types (Read, Write, Create, Delete, Share)
      * Second line is set for the User for Location ABC, showing (for instance) Read. Write, Create, Delete allowed while Shared is DENY
   * See indicative screenshot below    

This works.
* The ManagersGroup retains access to all the folders - since the subfolders inherit the permissions from the level above
* Each Location user sees ONLY the folder for their location, not for any others

Cautions
* You can lock yourself out if you control an item for Group Everyone with DENY properties.
* If you want to restrict privileges with Advanced Permissions, don't have "Everyone" with access to top level folder
* Never include DENY permissions for your ManagersGroup - since they are the ones who have the ability to update the Advanced permissions

![GroupFolders_ConfigExample](https://user-images.githubusercontent.com/42010857/102411085-bc139400-3ff1-11eb-9933-6e50e75f6adf.PNG)

![Location_ABC](https://user-images.githubusercontent.com/42010857/102410941-8a023200-3ff1-11eb-946f-9387f8ca4b58.png)

**Comment by chlarsen** [comment]
Dear Daksol,

Thank you so much for your detailed explanation; this is incredibly helpful.
Hugely appreciated!

Chris

**Comment by fschrempf** [comment]
@chlarsen I consider your case solved and close this issue. If you still miss something, please create a new issue using the template and make sure you check the [other ACL issues](https://github.com/nextcloud/groupfolders/issues?q=is%3Aissue+is%3Aopen+label%3A%22feature%3A+acl%22) for duplicates before.
