### ISSUE TITLE
Folder name on disk

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/groupfolders#108]
When I create a new group folder, it only shows up as the serialised folder in the __groupfolders folder. Considering that a complex implementation could have a very large number of Group Folders, this makes tying the serialisation of the folder to the corresponding Group Folder effectively impossible.

Why is this important?

Well, if I want to retrieve the files out of it at the file level (let's say I'm troubleshooting nextCloud stuff, or I have to access files at the filesystem level to retrieve data), this effectively becomes impossible due to the lack of connection between the serialisation and the Group Folder name itself.

This can be very easily solved by simply attaching the Group Folder name to the end of the folder. For example "##-FolderName".

Please?

**Comment by Djabal** [comment]
It can help also to migrate from a shared folder to a group folder.

**Comment by icewind1991** [comment]
The upcoming groupfolders release (to be released alongside nc15) will come with an occ command that exposes the mapping between folder id's and folder names to make things like this easier.

```
occ groupfolders:list
```

Adding the name to the physical folder isn't a great option since that would make renaming the folder a much more complex and expensive operation.

**Comment by dem36rus** [comment]
> The upcoming groupfolders release (to be released alongside nc15) will come with an occ command that exposes the mapping between folder id's and folder names to make things like this easier.
> 
> ```
> occ groupfolders:list
> ```
> 
> Adding the name to the physical folder isn't a great option since that would make renaming the folder a much more complex and expensive operation.

I apologize for updating the topic
I really need this option, I use “CIFS” for maindir and “OCC scan:file”. for interacting with files, webdav is not suitable for my tasks, because the problem is related to large files. the numbers in the name are inconvenient and bad, I am ready to donate funds to patreon to the person who will fix it, "Folder Id" +..+"Name" will completely satisfy my needs, 
Help me, thank you if you respond.

At least make a switch between naming modes. I am ready to rename a folder - a much more complex and expensive operation.
