### ISSUE TITLE
Unreadable admin view (in dark mode)

### ISSUE THREAD

**Issue by Sebastian-Maier** [nextcloud/groupfolders#1135]
Settings like the quota or the advanced permissions list are barely readable in dark mode (see screenshot).
I am aware that the dark mode is still in beta. In addition, I am not really sure whether this is a groupfolders or a Nextcloud bug.

<img width="1111" alt="Screenshot" src="https://user-images.githubusercontent.com/8041448/98675803-08b4e100-235b-11eb-8eb5-604f76cb675d.png">

**Comment by Ornanovitch** [comment]
Hi there. This is still an issue as of NC24.

**Comment by susnux** [comment]
Better but still some problem with NC 25.0.2 and groupfolders 13.1.0:

![open visual issues](https://user-images.githubusercontent.com/1855448/206731287-61d5ea67-408f-4c24-bbf8-b691c6813cb5.png)

* Permission check boxes do not use the same design as the `Advanced Permissions" checkbox
* Active entry in drop down is unreadable because of background color
* Input text is unreadable because text color
* Weird white edges on the quota dropdown
