### ISSUE TITLE
unexpected data access

### ISSUE THREAD

**Issue by obiper** [nextcloud/groupfolders#1298]
Problem:
A user creates a simple folder let's say "Customer01" within their nextcloud account and share this specific folder by creating a shared link. This user now gets a groupfolder attached with the same name "Customer01".
Now the user could only see the groupfolder within his account and the before created link to the share points now to the groupfolder content and not to the user folder.

Steps to reproduce:
1. User creates a folder within his root directory with a specific name "XY"
2. User creates a link to share this content
3. Groupfolders admin creates a folder with the same name "XY"
4. Groupfolders admin entitles the user to groupfolder "XY"
5. User is unable to see his before created folder "XY" and sees the groupfolder instead.
6. The old link to share the user folder points now to the groupfolder content!

Tested on Nextcloud 19.0.8 and 20.0.7

This behaviour could cause unexpected data access from third party.

**Comment by CoolMoDee** [comment]
And a second problem occurs: 
If a user has created a folder with name "XY" and the Groupfolders admin creates a groupfolder with the same name, the original folder of the user is no longer visible. It's still accessible via ftp (or similar) thru the servers filesystem but no longer accessible for the user.
As a result I get terrified user support requests, because they fear data loss.

If I share a similar named folder with somebody I get a additional number attached to the folder name. Maybe the same solution could be applied here.

**Comment by icewind1991** [comment]
https://github.com/nextcloud/groupfolders/pull/1239 Should fix name collisions like these
