### ISSUE TITLE
Show share initiator next to receiving user the same way it's shown for public links

### ISSUE THREAD

**Issue by loelkes** [nextcloud/groupfolders#1523]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

Users cannot see who shared a folder with another user. For share links the share initiator is clearly shown. 

<img width="497" alt="Screenshot 2020-05-17 at 13 37 47" src="https://user-images.githubusercontent.com/231909/82143365-9c41a500-9843-11ea-82e4-6ca6e4696e55.png">

**Describe the solution you'd like**

Show the share initiator the same way it's shown for Links.

![Untitled](https://user-images.githubusercontent.com/231909/82143406-12460c00-9844-11ea-8569-7d22951f3b04.png)

**Describe alternatives you've considered**

None

**Additional context**

Within a group folders it was unclear why a sub-folder folder was shared with another user. It was not possible for the users of the group folder to find out who had shared the folder in order to contact him for clarification.

**Comment by antong** [comment]
I also bumped into this. I did notice that if a folder is shared, then subfolders do show this sharing information!

**Comment by fschrempf** [comment]
@loelkes @antong @szaimen How is this related to group folders? Is this not a generic issue with shares in NC?

**Comment by antong** [comment]
> How is this related to group folders? Is this not a generic issue with shares in NC?

It may be a generic issue, but with normal shares there is the single owner that sees everything, and nobody else would be sharing subfolers. With group folders there is the whole group that can share subfolders. Other members have no idea who shared it. Best would be if other members also could remove and edit such shares, but without knowing who shared it, you can't even reach out to whoever did share.

**Comment by fschrempf** [comment]
> It may be a generic issue, but with normal shares there is the single owner that sees everything, and nobody else would be sharing subfolers.

Is that really the case? I can share a directory with multiple users and allow them to reshare. Doesn't this lead to the same problem without involvement of groupfolders.

**Comment by antong** [comment]
I'm sure you are right. I just haven't allowed people to reshare personal shares. But I have understood that the reason for groupfolders is to not have to have shared "folderadmin" accounts (that do the sharing and manage content). This issue is one in the category that makes groupfolders not live up to that.

**Comment by fschrempf** [comment]
> But I have understood that the reason for groupfolders is to not have to have shared "folderadmin" accounts (that do the sharing and manage content)

I don't think this is the right conclusion. It's a completely valid use case to have the same user do the sharing and manage the groupfolders and content). I just don't see how this is related to groupfolders in any way. If we would fix this, meaning implement a way to show the share owner in the UI, then we would need to do this in the files app or in the server core. I'm just trying to help finding out where this issue should be located.

> This issue is one in the category that makes groupfolders not live up to that.

Live up to what? Your expectations? Please provide clear feedback.

**Comment by antong** [comment]
> If we would fix this, meaning implement a way to show the share owner in the UI, then we would need to do this in the files app or in the server core. I'm just trying to help finding out where this issue should be located.

I'm sure you are correct that this is a generic issue and not limited to group folders.

> Please provide clear feedback.

Sorry, I'm trying! :-)  I Didn't mean to offend and I'm sorry if I was unclear. I'll leave this now and let the original reporter comment. 


I tried to convey one use case and workflow of group folders, but I'm happy to learn about better alternative ways to achieve this. Say a team needs to manage a folder together (content and sharing).  You can't have one individual do the share, because when that person is on vacation, goes missing etc., then other team members can't do anything about it. One way that has been used is to make a dedicated user account "team1" to which team members (people) have the credentials. The team members then log on with that account to manage content and sharing. Shared accounts are a bad security practice and a hassle for everybody involved. So I have seen groupfolders as a better alternative. You make a group "team1" and give it a groupfolder. This "alternative to a shared useraccount" use case and workflow is the background for what you refer to as my expectations. With that background it is an issue that one team member can't see who shared something (or unshare it, but that's a different issue).

**Comment by fschrempf** [comment]
> Sorry, I'm trying! :-) I Didn't mean to offend and I'm sorry if I was unclear. I'll leave this now and let the original reporter comment.

No worries, thanks for explaining and joining the discussion. I appreciate to hear your thoughts.

> So I have seen groupfolders as a better alternative.

This is the correct conclusion in my opinion and the way to go.

> You make a group "team1" and give it a groupfolder. This "alternative to a shared useraccount" use case and workflow is the background for what you refer to as my expectations. With that background it is an issue that one team member can't see who shared something (or unshare it, but that's a different issue).

I think that can be considered a bug in the groupfolders app (see #642). But why don't you use the ACL ("Advanced Permissions") feature for your use-case? This sounds like it might work out much better for you than using sharing.

**Comment by fschrempf** [comment]
I'm closing this assuming the issue is resolved through the discussion above. Feel free to create a new issue or comment on the existing issues if you think there is something that should be changed.
