### ISSUE TITLE
Renaming folder in Desktop Client deletes data

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/groupfolders#1816]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a groupfolder, share the folder with other people, add some files
2. Open Nextcloud folder in explorer (Windows). Rename the group folder.

### Expected behaviour
Renaming should be forbidden or, it should create a local *copy* of the folder.

### Actual behaviour
folder is renamed and becomes a private/personal folder. the group folder on the server still exists, but now is completely empty. the client re-syncs that empty folder.

This means the person that renamed the folder now has an empty group folder + a private copy of the former group folder incl. all the files. All other persons are left with an empty group folder.

As this action is not shown in "Activity" there is absolutely no chance to find the person who renamed the folder and copy the data again from his folder.

**Comment by CarlSchwan** [comment]
That's a difficult issue to solve unfortunately :/

For the Nextcloud desktop client, it's not really possible to make it so that a folder can't be renamed/moved by the user. The basic read/write/execute permissions on Linux are not sufficient to block the renaming. This means we would need to add a custom metadata on files and tell every file manager to not ignore them (this includes proprietary file manager on Windows and macOS).

Also blocking just renaming the root folder, is like `sudo rm -rf /` not working anymore but `sudo rm -rf /*` still working file since it's not removing / but just all the content inside. it's not really a solution.

Now for how to recover from this situation. An idea would be to look at the trashbin, the files should all still be inside.

**Comment by fschrempf** [comment]
To limit the impact of this issue one might consider denying "delete" permissions for the majority of users of the groupfolder. This should at least reduce the probability of someone accidentally renaming the groupfolder. Of course this doesn't work if those users need the ability to delete files for other reasons.

**Comment by xbluemonkx** [comment]
@fschrempf we use group folders to provide a space for teams to work together and manage their files. we use groupfolders to be able to manage those folders and to avoid the file-ownership problem of files that "belong to the team/to everyone". because if someone quits we want to be sure that those files are user-intependent.
therefore it is not possible for us to revoke the delete-right.

@CarlSchwan - the problem is that those files do not go to *everyones* trash bin. So if you do not know who renamed the folder, you do not know in whose trashbin you have to search for those files.

**Comment by acsfer** [comment]
@xbluemonkx there is a Group Folders, inside `/datadirectory/__groupfolders/trash`

**Comment by xbluemonkx** [comment]
@acsfer thanks for the hint. still not ideal, but makes me feel way more comfortable, when I know that i can get back that data. :)

**Comment by PVince81** [comment]
As far as I remember, the desktop client should already know what it's allowed or not if the exposed permissions are correct.
I do remember a recent issue where it was said that the permissions were not exposed correctly, @CarlSchwan @camilasan do you remember which ?

The client cannot block the rename but it can refuse to sync the folder until it's renamed back, or it can redownload the original one instead of deleting its contents. For this behavior to work correctly, we must ensure the permissions are exposed correctly.

cc @tobiasKaminsky

**Comment by xbluemonkx** [comment]
@PVince81 yes, I have seen this. @allexzander mentioned the ticket above. I am very happy to see, that this problem is taken care of so fast.
