### ISSUE TITLE
Ability to select individual users

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/groupfolders#1841]
Currently you can choose a group it would be nice to have a option for user dropdown or search

**Comment by CarlSchwan** [comment]
I don't think adding the ability to directly select individual users is something we want to implement since that seems to be something going against the goal of this app. It's named groupfolder for a good reason :)

If you want one individual to access a group folder, you can do:

* Add the individual to a group that has access to the groupfolder
* Create a special group for the user and add them add the group to the groupfolder
* Just share the groupfolder with the user

Do you have an idea of a special usecase, not covered by the above solutions?

**Comment by andyxheli** [comment]
@CarlSchwan thanks for the reply. Makes alot of sense. Unfortunately, I do not.
