### ISSUE TITLE
Transferring ownership of groupfolder should not be possible

### ISSUE THREAD

**Issue by vanpertsch** [nextcloud/groupfolders#1967]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
- create group1
- create user1 und user2 users as members of group1
- create group folder gf1 with sharing rights for group1
- login as user1 
- go to settings -> sharing
- select transfer ownership, select gf1 and user2

### Expected behaviour
group folder should not be selectable because per definition group folders have no specific owner

### Actual behaviour
ownership transferral is offered and partially (?) successful. User2 received acceptance request, and after accepting a folder "transferred - xyz" is created - albeit empty (?, not checked further wether later on files will be copied). The original groupfolder still does exist.

### Server configuration

**Nextcloud version:** 23.0.3

**Comment by icewind1991** [comment]
it could check if the file is from the user's home storage

`$node->getStorage()->instanceOfStorage(IHomeStorage::class)`

**Comment by unteem** [comment]
Hi

So now it seems that with https://github.com/nextcloud/server/pull/32149 it is not possible to transfer a group folder to a user. 

It would be actually quite nice if we could transfer a group folder to a user. It was actually broken, transfer was working but the folder had 0 in size.  https://help.nextcloud.com/t/folder-ownership-transfer-does-not-transfer-folder-size/120231

To be honest group folder has been unusable for us, too many bugs, fixing those look like quite some work so we had to revert back to using normal users. Being able to transfer a group folder is a nice feature. 

I guess that instead of not allowing we could check if the user making the transfer is either a system admin or a sub-admin of the group. That seems trivial ? 

Fixing the 0 size issue that I don't know where its coming from :upside_down_face: 

I can have a look or if you have ideas @icewind1991 ?

I'm up for the task but I need directions as I'm not a php expert neither I know how transfer works. I want this features upstream and not make a custom script on my side as we have been doing so far with sql queries. I'll do my homework but yep help is always appreciated. 

Should we close this issue and create a new one ?
