### ISSUE TITLE
Cannot give higher permissions if no main permissions are set

### ISSUE THREAD

**Issue by Commifreak** [nextcloud/groupfolders#2018]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a new group with a few users in it and a new group folder and assign that new user group
2. Give the user group NO rights: 
![grafik](https://user-images.githubusercontent.com/87267/172769369-39941b27-e29f-46a7-a126-e8d4beef0728.png)

3. Enable ACL:
![grafik](https://user-images.githubusercontent.com/87267/172769445-4300d70c-9395-4a8e-bbba-a5c307c205ab.png)

Go to that folder. At the beginning, all is ok: 
![grafik](https://user-images.githubusercontent.com/87267/172769519-504eddde-5d7a-464d-b7f8-6cf364e95590.png)

But now I want to change this via ACL, so for testing I give myself full rights for the root folder:
![grafik](https://user-images.githubusercontent.com/87267/172769611-ed767172-d305-469a-880a-481ed63849de.png)

But that changes nothing. Iam not able to do anything. Same for subfolders inside that group.

Am I missing something?

### Expected behaviour
Respect set ACLs

### Actual behaviour
It seems, that ACLs are ignored somehow

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** Apache 2.4

**Database:** MySQL

**PHP version:** 8.0

**Nextcloud version:** 24.0.1

**Group folders version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** .zip

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** FF 101

**Operating system:** Qin 10

### Logs

--

#### Web server error log
--

#### Nextcloud log (data/nextcloud.log)
--

#### Browser log
--

**Comment by fschrempf** [comment]
The handling of "normal" group folder permissions vs. advanced permissions is one of the things that is really not intuitive and often causes unnecessary confusion. But the fact is, that this is currently expected behavior as documented in the README: _Denied permissions configured for the group folder itself cannot be overwritten to "allow" permissions by the advanced permission rules_.

If you ask me the whole permission system needs to be reworked from the ground up, but I don't think this will happen anytime soon, if at all. Please also see https://github.com/nextcloud/groupfolders/issues/655 for further information and discussion.
