### ISSUE TITLE
Move Files not working

### ISSUE THREAD

**Issue by DerSeb90** [nextcloud/groupfolders#243]
If I move a File inside the group Folder to an Subfolder or an private Folder the File can't be moved.
My group has no delete rights in this Group Folder. Is the Problem that moving Files is practically Copy&Delete?

System: Ubuntu 18.04
NC Version: 15.0.0.10
PHP Version:  7.2.13
WebServer: nginx
Group Folders Version: 2.0.0

**Comment by SebSeifert** [comment]
1 Month and no comment? It should be more than 1 with this problem?

**Comment by kokotko1337** [comment]
@SebSeifert GroupFolders is official app, but i have feeling that is not wanted baby .... Which is funny, because it is key feature for Enterprise ... Im sitting on version 13, because im scared to upgrade :D

**Comment by SebSeifert** [comment]
Yes but it seems not to be an GroupFolders related Problem. It's in normal Shared Folders still the same Issue.

**Comment by Henk57** [comment]
It is related to Groupfolders I think. Deleting files and folders within a groupfolder lead to inconsistencies with the database. The app even causes trouble deleting other files outside groupfolders. The occ command to clear the trash doesn't work even. Occ behavior is also affected by the app. Others came to this conclusion since NC 14. It is not solved in NC 15

**Comment by MaxGitHubAccount** [comment]
I'm having the same problem. I cannot move any file from any folder or my root filesystem of nextcloud to a shared folder.
I'm on nextcloud 16.0.4 running on debian buster with group folder 4.1.0 but this problem already existed for nextcloud 15, stretch and the corresponding group folders for me.

This is probably related to: https://github.com/nextcloud/groupfolders/issues/429

**Comment by ElmarJongerius** [comment]
Same issue. Group folders started misbehaving when moving or renaming files/folders.

**Comment by AstroGD** [comment]
Same issue here. I am not able to move any files nor just upload them. I need to Upload files up to 20 times until I get a "this file already exists" dialog and the file finally shows up. Moving does not work at all - I literally tried moving the same file 50 to 100 times in a row but the only thing I achieved were so many "an unknown error occurred" notifications that I flooded my screen with them. This issue is up since 2018 - and there's no fix since then? I mean that is a key issue in the plugin and it makes my nextcloud unusable... And this is an official Plugin so it definitely damages the reputation of official plugins because when this plugin is faulty and no one fixes it, what does that mean to bugs that will show up in the future? Do I need to wait more than 2 years every time a plugin stops working until the issue is resolved? To be honest I thought the official plugins get properly tested before release or at least bugs that are being found and submitted get fixed asap...

**Comment by ElmarJongerius** [comment]
Possible solution for some of you:
- My issue was, that moving or renaming files within the nextcloud didnt work (403 forbidden to move) once they were already synced. I was using the windows app for this.

I (finally) resolved this by revoking access to my windows client, and loggin in again.

**Comment by AstroGD** [comment]
Thank you for sharing this solution with everyone.
Sadly it doesn't work for me. 
I'm using NextCloud in the Browser and on my Phone - Both are unable to move Items.
On the Phone I get "You are missing permission to move this Item" (I hope I translated the error correctly as it gets displayed in german).
I am using my administrator Account for this but haven't uploaded the Pictures myself.
The person that uploaded the files directly into the group folder is also not able to move the files so I assume it doesn't have something to do with who uploaded the files.

**Comment by chrstn-hntschl** [comment]
Stil an issue in Nextcloud Hub (aka 18). Cannot move files from outside a newly created group folder into that group folder ("Could not move xxx"). Currently I will abandon group folders at all since the risk of data loss seems to high!

**Comment by Henk57** [comment]
Oh boy. We're one year after, and this problem still isn't solved. Will it be?
I also installed release 18.0.0 and got some strange misleading warnings. Fact is that this release is not as stable as i'd expect. Collabora plugin is installed, but does not show up in the menu. OnlyOffice does.
And I got the warning that the virusscanner is disabled, but it is sttiil enabled.
Perhaps Nexcloud should stop with new high level releases and first solve all existing problems.
And chrstn-hntschl, have look at my posts concerning the issue and how to 'clean' the database. I also gave a sollution for an alternative approach for Group Folders in an other thread by creating a 'special user' that owns the Group folders that one wants to share. When everything works, the content can be copied/moved to the Group Folders later.

**Comment by AstroGD** [comment]
I've got a little more information on the error that occurs at my Nextcloud instance:
In the Browser the error looks like this
![image](https://user-images.githubusercontent.com/35271072/73122048-53a66900-3f80-11ea-87e4-ca71a4fa7fb7.png)
(Translates to "Imagename" couldn't be moved.)

In JS-Console the following error is being printed:
![image](https://user-images.githubusercontent.com/35271072/73122058-7c2e6300-3f80-11ea-8641-f96ac5ae028a.png)
The request is being sent to /remote.php/dav/files/username/Groupfoldername/Filename which fails with Code 403 (Forbidden)

On Android I also get a message that tells me I'm lacking permission to move files.
I would really appreciate any solution right now even if that means completely reinstalling nextcloud (again)

Groupfolder version I'm using is 5.0.5 on NextCloud V17.0.2
If you need more information to this error like a list of installed Packages or so please tell me I'm more than happy to help in any way possible, but not responding at all is the worst you could do as it just frustrates the users and doesn't get this error fixed like it is supposed to be!

It would be great if someone who's working on the code at least comments here saying why it is not being fixed!

Im now at a point where I hope randomly pinging contributors might help (please don't be angry and respond with at least a "sorry we can't do anything for ya" so that I'm not stuck at hoping and look for an alternative way to nextcloud Group Folders or nextcloud all together)
@icewind1991 @juliushaertl @nextcloud-bot

**Comment by AstroGD** [comment]
More Information to this issue (I'm trying to give all information I can find):

- I have all permissions on the folder to move from and to
![image](https://user-images.githubusercontent.com/35271072/73122353-1f34ac00-3f84-11ea-8fa6-eab311d574a8.png)

- All files and folders insider the groupfolder are being found
![image](https://user-images.githubusercontent.com/35271072/73122372-76d31780-3f84-11ea-82de-fdabe1203c61.png)

- I am not able to move files in any of the folders I've created

- I cannot move files that were created by me (admin privileges) or another user (user privileges) and the user can also not move any of the files

- Also the folder I was trying to move files to randomly disappeared during my tests and I had to recreate it

`- I am not able to move files in any of the folders I've created` is only partially true:
I tried to move files during testing of the error and for some bizarr reason one file was moved after like 5 minutes but the error was being shown previously. After trying to move the file back I got the error that the file already exists in the destination folder but wasn't present. I then spammed cron.php like 30 times and now the file has appeared but is now present in the source AND destination folder (Maybe it has nothing to do with the cron spamming but I'm not able to reproduce anything consistently to be more precise. Dealing with this plugin is a total mess of luck and frustration)

**Comment by dcotegpg** [comment]
Any comments or possible solution to this? I'm having the same kind of issue while copying files from private folders to Group Folders subfolders. Here is the log I have for this error:
![Screenshot_45](https://user-images.githubusercontent.com/10233898/89033555-075c2d00-d305-11ea-9505-408493b4f054.png)

**Comment by ronaaron** [comment]
Having the same problem with v20.

**Comment by tajecarterja** [comment]
I am having the same problem as well.

**Comment by pierreozoux** [comment]
I couldn't reproduce, I'll close, but feel free to reopen.

**Comment by HLeithner** [comment]
I have a similar problem but only for PDF files, I can't move them and can show details. The readme.md file can be moved without problems. I see nothing in the debug log.

**Comment by pierreozoux** [comment]
@HLeithner then please open a new bug.

**Comment by HLeithner** [comment]
@pierreozoux ok will do, it's maybe unreleated to groupfolders sry for the noise

**Comment by pierreozoux** [comment]
no problem :)

**Comment by edvanleeuwen** [comment]
I have this issue with NC 25 and GF 13.1.1.

I cannot move, delete files within the groupfolder. Neither through the UI nor the client. I see no errors in the log, just a message that it cannot be executed.

I can move, delete with normal files and shares.

Could you please reopen it?
