### ISSUE TITLE
Store groupfolders not with id's but with folder names (like with usernames)

### ISSUE THREAD

**Issue by 13hannes11** [nextcloud/groupfolders#252]
I would prefer if there was the possibility to store group folders by name not by id because this would crawling files with scripts on my server much easier.

**Comment by bpcurse** [comment]
Absolutely +1 @13hannes11
It is hard to identify the correct folder in the file system. Ran into this problem several times.

**Comment by riesinger** [comment]
This would be perfect for our application:
In our college dorm, we provide a nextcloud share for everyone.
Nextcloud is running in a VM and the storage for each group gets mounted into it via NFS. We currently use the external storage plugin to use those external mount points, but this plugin does not provide permissions (like read-only, write, share, ...).
Storing the group folders would enable us to mount the NFS shares directly into nextcloud's data directory (which currently would technically work but be a mess, because you cannot properly identify group folders by their ID)

**Comment by fschrempf** [comment]
Quoting @icewind1991 in https://github.com/nextcloud/groupfolders/issues/1183#issuecomment-798770263:

>> Is it possible to have a new occ groupfolders:group command that accepts the Group Folder name instead of the Group Folder Id?

> No because the folder name is not unique

I think this is reason enough to mark this as "won't fix". And it feels like there should/could be other/better solutions for the use-cases described above.

**Comment by icewind1991** [comment]
Agreed
