### ISSUE TITLE
Feature request: Sharing with single user

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/groupfolders#28]
Sometimes you might want or need to share a folder not only with groups, but also with additional users that do not / should not belong to one of the groups. Of course there is an easy workaround to set up another group just for this user, but it's not a clean approach and fills up the groups list.

It seems to be useful to have another option for r/w or r/o sharing with single users, although I know the name is **group**folders.

**Comment by dan-nkl** [comment]
I don't think that this is really needed.
Adding the user to a group is absolutely simple and should be enough.

**Comment by lmctv** [comment]
I think there should be a way to create global shared folders, with the provision to let some users re-share them with both users and groups.

Another **very** important feature would be an option to "granfather" an already created admin-owned folder as a share folder.

**Comment by putt1ck** [comment]
You can reshare a group folder (though note with bugs at the moment, with recommendation to use share by link as a functional workaround), which takes care of this use case, I think? cc @lmctv @bpcurse

**Comment by lmctv** [comment]
No, I'd consider resharing a work-arounds at best. If I'm creating an ad-hoc shared folder for a project run by a group, with another person who should work on that project, but should not be granted access to other resources allocated to the same group, I'd rather have that status visible upfront from the share properties.

**Comment by putt1ck** [comment]
Possibly I'm not understanding the use case scenario. For me it seems that resharing the adhoc shared folder with the individual prevents the individual from accessing other resources shared with the group. This works in 2 scenarios I can see e.g.

(i) group folders 1, 2, ..., X, shared with group A and group A (admin); group folder 1 then reshared by group A (admin) with Ext Person, or
(ii) group folder 1, shared with group A and group A (admin); sub folder 2 for project created within group folder 1 by group A (admin) and shared with Ext Person.

In either case above the status of the share with external person will be visible to those with authority to share - and once the patch https://github.com/nextcloud/activity/pull/190 is in the activities app, rather more visible to members of the team than if that sharing was done at the group folder level, which would reduce the risk that group members accidentally add material which shouldn't be shared with an non-group member.

**Comment by ZeikoFr** [comment]
Hi @bpcurse This features is now available with the ACL provided with group folder.

Can you close the issue ?

Thanks

**Comment by bpcurse** [comment]
@ZeikoFr Although it is possible to select single users through the ACLs these users need to be added to the groupfolder first, but adding a single user is still not possible. The (ugly) workaround is to create a group for each individual user and add the group.
In my opinion this is an important function that is still missing.

Last checked today on Nextcloud 19.0.6 / Groupfolders 7.1.1

**Comment by pierreozoux** [comment]
Developing a software is sometimes also saying no.

By the name here, it is a folder for groups, I don't think it will be ever fixed.

I'll close it, but if you have a strong feeling, feel free to reopen.

**Comment by alexanderdd** [comment]
Too bad, we need this too. 

The situation is that folders are shared with certain groups, but sometimes there is this one person that should also have access but should not be part of one of the groups because they should not have all the privileges that come with being a member of that group.
And no, we cannot use regular shares because when I delete a user, all files that this user created will be gone, so I need to do everything in group folders.

**Comment by putt1ck** [comment]
Add group with the individual user in it (maybe like an "all staff" for most flexibility) to have appropriate access to the group folder. Enable advanced permissions for an appropriate group(s)/person(s) for that group folder.
If what the person should have access to is in the root of the group folder, add an ACL allowing them access, and another removing access for the "all staff" group. Adjust as necessary for subfolders.

This approach fits the logic of group folders while providing for moving the fine-grained controls to the responsible parties which makes more sense in a organisational sense (you can of course still have IT support doing it, but it shouldn't be unless they are people responsible for deciding who has access to content).

**Comment by foolfitz** [comment]
Hi — I'd like to respectfully revisit this, per pierreozoux's invitation to reopen if someone feels strongly. We do, and we already have a working implementation we're happy to contribute.

### Why this still matters (and isn't covered by existing options)

The recurring use case (raised here by alexanderdd and bpcurse) is: a folder is shared with one or more groups, but **one specific person** also needs access **without being put into any of those groups** — because group membership would grant them unrelated resources.

The existing workarounds don't really cover it:
- **A one-user group** works but clutters the group list and is an admin headache at scale.
- **Advanced permissions (ACL)** can *target* a user, but only if they're already in the folder via a group — so it can't grant initial access to an outside user.
- **Normal sharing isn't a substitute**: deleting a user removes files they created in a regular share. Group folder data is owned by the folder, not the user, which is exactly why these admins must keep everything in group folders.

On "by the name, it's a folder for *groups*": the app already extends past plain groups (Teams/Circles, per-user ACL mappings). Granting an individual user is the natural, ACL-consistent next step, and it composes cleanly with advanced permissions.

### What we've built

Implemented and validated end-to-end on a real 31 instance (mount, per-permission granularity, revoke→unmount, permission union with group access, cleanup on user deletion). It mirrors the existing group mechanism:

- New `oc_group_folders_users` table `(folder_id, user_id, permissions)`, mirroring `group_folders_groups`.
- Direct-user folders merged into `getFoldersForUser()` / `getFolderPermissionsForUser()` with the **same OR semantics** as groups/circles.
- Cleanup wired to `UserDeletedEvent` and folder removal.
- An **instance-wide async user search** (`GET /folders/{id}/users/search`) so admins can add users outside the folder's groups — deliberately *not* the folder-scoped ACL search.
- REST endpoints mirroring the group ones, regenerated OpenAPI, a "User" column in the settings UI, and unit tests.

It's on a `stable31` base for our own deployment; we'd forward-port it to `master` for the PR.

### The ask

Before we invest in the `master` forward-port: **would the maintainers be open to a PR for this feature?** If yes, we'll reopen/track here and open one against `master`. If it's still "no" by design, we understand completely and will keep it as a downstream patch — we'd just rather ask first than do the work twice.

Thanks for considering it.
