### ISSUE TITLE
Permission issue

### ISSUE THREAD

**Issue by Mululu** [nextcloud/groupfolders#2934]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a group folder and assign 2 groups. 

2. Group 1 read, write
3. Group 2 read, write, delete
4. Try deleting folder with user in group 2

### Expected behaviour
Users in group 2 should be able to delete

### Actual behaviour
User from group 2 cannot delete because he is also in group 1 and is not allowed to delete group 1. The higher permission in this case, allowing deletion, should override the deletion note

Nextcloud Hub 8 (29.0.0)

**Comment by XueSheng-GIT** [comment]
Just tried with my NC29 test installation and followed your step. But actually user in group2 is able to delete.
Please double check whether the steps to reproduce are complete. Thanks.

**Comment by Mululu** [comment]
Hello,

I tried a few things back and forth, but unfortunately to no avail. This error is causing major problems in our organization. Steps I have now taken
- Deleted all permissions using the database and reset them >> no improvement

To narrow down the error further, I have done the following. 1 & 2 work as expected, but the error already occurs in 3., which is why I started the post. 
### 1.
- The "Admin" group gets all rights for the main "Images" folder
- The "All" group does not get read rights

Result Users in the "Admin" group can see the "Images" folder // Users in the "All" group cannot // Users who are in the "Admin" group and in the "All" group at the same time can see the "Images" folder. >> **Works**

### 2.
- The "Admin" group gets all rights for the main folder "Pictures"
- The "All" group gets **only** read rights

Result Users in the "Admin" group can see the "Pictures" folder // Users in the "All" group can also see the "Pictures" folder // Users who are in the "Admin" group and in the "All" group at the same time can see the "Pictures" folder. >> **Works**

### 3.

- The "Admin" group gets all rights for the main folder "Pictures"
- The "All" group gets **only** read rights
- The "All" group is denied the "Read" right for a **subfolder** "Tablet". Result Users in the "Admin" group can see the "Pictures" folder and the "Tablet" subfolder // Users in the "All" group can also see the "Pictures" folder, but not the "Tablet" subfolder // Users who are in the "Admin" group and the "All" group at the same time can see the "Pictures" folder **but not the "Tablet" subfolder** >> **Does not work as intended**

Expectation: Users who are in the "Admin" and "All" groups at the same time should see the "Tablet" subfolder. So to speak, the "Admin" group's read permission should be higher than denying read rights to the "All" group. 

I suspect that the permissions are not being passed on to the subfolders correctly!? 

I hope I made it clear.

**Comment by XueSheng-GIT** [comment]
I assume you are mixing up general Access rights via Admin settings and ACL.
Please be more precise where you did those access restrictions. For me is also not clear whether you created nested groupfolders or not.
Maybe screenshots for the non-working example would be helpful (admin settings + ACL).

**Comment by Mululu** [comment]
The main rights are assigned in the settings. However, since there are also subfolders in the group folder that not everyone should see, the ACL permission is required there. ![image](https://github.com/nextcloud/groupfolders/assets/5918495/8ef91340-a7b5-4b0f-b7d1-e602f4784c88)

What you can also see in the following image is that rights are displayed incorrectly. The general rights from the settings (image above) are not displayed as standard (inherited) but are generally shown as denied. Main folder
![image](https://github.com/nextcloud/groupfolders/assets/5918495/c4cde1f9-0447-48a3-a3fa-b8183ce78307)

But then shown as allowed again in the subfolder
![image](https://github.com/nextcloud/groupfolders/assets/5918495/e4a32e7a-78ad-4c0d-a9b7-238dd460bb82)

Variant 2 (as described above)

Here the folder is visible to the Admin and Everyone groups, as defined in the basic settings. However, the display is incorrect as described above. ![image](https://github.com/nextcloud/groupfolders/assets/5918495/ebe0d0dd-a396-4697-a5b9-8c79b3b62dfc)
Subfolder "Tablet" visible according to basic setting rights
Display group "Admin" correct, display group All incorrect >> according to basic setting no share and no deletion rights. Read, write, create >> correct
![image](https://github.com/nextcloud/groupfolders/assets/5918495/10614d96-96c1-4878-ba05-f16c3c4b7de0)

Variant 3 (as described above)
Read rights for group All on subfolder Tablet denied
![image](https://github.com/nextcloud/groupfolders/assets/5918495/0d5bb3ec-4896-4c1c-8830-b5d4baa70ce1)

Result
Users who are in the group All can no longer see the folder >> so far so good. Users who are only in the group Admin can still see the folder >> just fine. However, if I add the user to the group All, the folder is no longer visible.

**Comment by XueSheng-GIT** [comment]
On the frist view I would say as expected. ACL deny does overwrite general permit. Try to add a ACL grant to read for Admin and double check again. But I assume that also deny acl does overwrite grand acl.

Regarding displaying of inheritance, I think there's already an issue for this (probably also a fix).

**Comment by XueSheng-GIT** [comment]
Please also double check whether your issue is a duplicate of https://github.com/nextcloud/groupfolders/issues/2812.

**Comment by fschrempf** [comment]
Maybe related or even fixed by: https://github.com/nextcloud/groupfolders/pull/2870

**Comment by Mululu** [comment]
> On the frist view I would say as expected. ACL deny does overwrite general permit. Try to add a ACL grant to read for Admin and double check again. ~But I assume that also deny acl does overwrite grand acl.~ Maybe a more correct description: #2828
> 
> Regarding displaying of inheritance, I think there's already an issue for this (probably also a fix).

Unfortunately, I have to disagree with you because the regulations are such that approvals override refusals.

![image](https://github.com/nextcloud/groupfolders/assets/5918495/b909482e-295b-4d00-bd9b-b6755650f4f1)


> Maybe related or even fixed by: #2870

I'll look at it tomorrow

**Comment by Mululu** [comment]
So I have no idea what has changed in Nextcloud 29 or in the Groupfolder app, but something is wrong here. According to the documentation, the allow right should override the deny right. This has worked for me in the past. And from now on it no longer works without any changes to the rights.

Maybe something has been messed up here? @https://github.com/nextcloud/groupfolders/pull/2902

**Comment by chaosgrid** [comment]
I think this is the same issue as https://github.com/nextcloud/groupfolders/issues/2812 because in general, inherited "allow" permissions do not take precedence over explicit deny permissions in the current folder. This behaviour changed somewhere within the last year.

**Comment by Jerome-Herbinet** [comment]
@icewind1991 I would like to draw your attention to this thread.

**Comment by fschrempf** [comment]
> What I can't find anywhere is what does occ config:app:set groupfolders acl-inherit-per-user --value true do?
Is this new or when was it introduced?
What happens if it's true? What happens if it's false? I couldn't see any change.

Once again some feature was added without documentation. You have to read through the description in the PR here: https://github.com/nextcloud/groupfolders/pull/2870#issue-2192820789. This should give you an idea what the new option is about. This was only added a few weeks ago and it seems like it has been backported to NC 26 to 29.

**Comment by Mululu** [comment]
Ich verstehe es nicht. 

Muss ich nun acl-inherit-per-user auf true oder false setzen um das bisherige Verhalten wiederherzustellen oder geht das nicht mehr? So eine Änderung ist total ärgerlich!

**Comment by dorianne-arawa** [comment]
To restore old ACLs (prior to Groupfolders versions 14.0.6, 15.3.3, 16.0.2 and 17.0.0), you need to set the `occ config:app:set groupfolders acl-inherit-per-user --value` parameter to `true`. In this way, the old ACL operating mode remains available. I hope this information will help you @Mululu and @fschrempf 

This setting is the result of Nextcloud correcting a bug in Groupfolder. This bug was being exploited by many users (as it was not easy to identify). This correction therefore implies a change in the expected behavior of Groupfolder ACLs on the part of users who were exploiting this bug. (intentionally or not) 
Following a collaboration between Nextcloud and Arawa, this setting has been implemented to allow both modes of operation, according to user preference. 

To my knowledge, there is no documentation on this yet. Arawa plans to write one as soon as possible to provide a clear view of these changes and the impact of this new configuration. 

Damour Dorianne
Arawa

**Comment by Mululu** [comment]
I have now executed the occ config:app:set groupfolders acl-inherit-per-user --value true. However, it doesn't work properly, here are 3 videos:

User is in group "Admin" & group "All"

Video 1: General assignment of rights for groups, locking the "Tablet" folder for the "All" group, folder no longer visible even though users are also in the "Admin" group

Video 2. Inheritance should be basically on, but selected again, folder not visible.

Video 3. Admin group explicitly given read rights, folder not visible

Video 4. Inheritance display error?

In general, it seems to me that there is a bug with inheritance!?

<iframe src="https://player.vimeo.com/video/947520830?h=29ac67c471" width="640" height="564" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
<iframe src="https://player.vimeo.com/video/947520830?h=29ac67c471" width="640" height="564" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
<iframe src="https://player.vimeo.com/video/947520830?h=29ac67c471" width="640" height="564" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
<iframe src="https://player.vimeo.com/video/947523572?h=600f35b2fa" width="640" height="564" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>

**Comment by chaosgrid** [comment]
> > What I can't find anywhere is what does occ config:app:set groupfolders acl-inherit-per-user --value true do?
> > Is this new or when was it introduced?
> > What happens if it's true? What happens if it's false? I couldn't see any change.
> 
> Once again some feature was added without documentation. You have to read through the description in the PR here: [#2870 (comment)](https://github.com/nextcloud/groupfolders/pull/2870#issue-2192820789). This should give you an idea what the new option is about. This was only added a few weeks ago and it seems like it has been backported to NC 26 to 29.

Thanks, setting this to true re-activates the old behaviour. In the future, it would be good to document these changes since this is a critical permission behaviour and I think many people were locked out of folders due to this change. In general, old behaviour should have priority over activating a new critical permission behaviour for everybody by default.

**Comment by Mululu** [comment]
But the problem is not yet solved! True doesn't seem to perform the old behavior correctly see my post with the videos...

https://github.com/nextcloud/groupfolders/issues/2934#issuecomment-2118232859_

**Comment by Mululu** [comment]
!?!?

**Comment by Jazz7584** [comment]
> To restore old ACLs (prior to Groupfolders versions 14.0.6, 15.3.3, 16.0.2 and 17.0.0), you need to set the `occ config:app:set groupfolders acl-inherit-per-user --value` parameter to `true`. In this way, the old ACL operating mode remains available. I hope this information will help you @Mululu and @fschrempf
> 
> This setting is the result of Nextcloud correcting a bug in Groupfolder. This bug was being exploited by many users (as it was not easy to identify). This correction therefore implies a change in the expected behavior of Groupfolder ACLs on the part of users who were exploiting this bug. (intentionally or not) Following a collaboration between Nextcloud and Arawa, this setting has been implemented to allow both modes of operation, according to user preference.
> 
> To my knowledge, there is no documentation on this yet. Arawa plans to write one as soon as possible to provide a clear view of these changes and the impact of this new configuration.
> 
> Damour Dorianne Arawa

Worked for me thx.

**Comment by dorianne-arawa** [comment]
Hi @Mululu , 


I don't know if your problem has been solved. 


Could you please tell me which version of the Group folders application you had installed when you wrote your comment containing the 4 videos? 
Reading your videos, I don't see the “ dashes ” for inherited rights, never set manually, which makes me wonder about the version. 

Could you also confirm that the “occ config:app:set groupfolders acl-inherit-per-user --value” parameter was set to “true”? The problems seen in the videos seem to be solved if the parameter is set to “true”. 

In video 1: I've reproduced the problem as best I can on an instance, and my user being in “admin” and “Alle” can see the “Tablet” folder after reloading. But if the “false” mode is activated for the new parameter, the result is that this same user can no longer see “Tablet” (in the case of inherited and manual rights, it's the manual right that takes priority when the mode is set to “wrong”).

In video 2, my thoughts are similar: the manual “false” read right of “Alle” overrides the “true” read right of “admin” if the “occ config:app:set groupfolders acl-inherit-per-user --value” parameter is set to “false”. At “true”, “admin” should see the folder. The same applies to video 3.

After various tests, I noticed that when the parameter “occ config:app:set groupfolders acl-inherit-per-user --value ”is set to : 

- "false": we have the new operating mode, following a bug fix (which should have been the initial operating mode, but was not effective because of the fixed bug in question): if you only have inherited rights, the most permissive right applies. If you only have manual rights, the right of the nearest relative set manually (by going up the tree) applies. If you have a mixture of both inherited and manual rights, the manual rights apply, and if two inherited rights are different, then the MANUALLY SET NEAREST PARENT right (going up the tree) applies.

- "true": we're back to the way things worked before, but without the bug and with proper inheritance of rights: whether permissions are inherited or manual, or both mixed on a folder, the most permissive right applies. If there are dashes somewhere, it means that the right has never been manually entered in the database (but a “true” or “false” right still applies, but I don't know which). 

I hope this will help you or others.

**Comment by level420** [comment]
@dorianne-arawa but a dash means `inherited` in both cases, means indifferent  from `occ config:app:set groupfolders acl-inherit-per-user --value` set to `true` or `false`, or am I wrong here?

**Comment by dorianne-arawa** [comment]
I think you're right @level420 . It means inherited in both case. But it's inherited rights when you only click on the user or group in the advanced permission, and define nothing. I don't know which right apply (true or false). It herits from the nearest parent. 

Maybe those 2 links can help you too : #3067 and https://github.com/arawa/nextcloud-groupfolder-acl-flattener (trying to fix the dashed with script, but it's dedicated this is dedicated to the transition from the old version of GF without dashes to the new version with dashes, to be done in one time)

**Comment by provokateurin** [comment]
Duplicate of https://github.com/nextcloud/groupfolders/issues/598
