### ISSUE TITLE
No synchronisation of shared folder with trailing whitespace in name using desktop client

### ISSUE THREAD

**Issue by pflasterix** [nextcloud/groupfolders#296]
A shared folder will not be synced by default via the windows dekstop client if the name of the folder ends with a whitespace character.  Additionally, the folder does not appear in the desktop clients folder tree.

Test system:
Windows 10 x64
Windows Desktop Client
Version 2.5.1final (build 20181204)

Nextcloud Release 15 running on an apache Webserver.

I was able to circumvent this issue by removing the trailing whitespace using the web app. In an instant, the sync completes successfully and the missing folder (and its contents) becomes visible as expected.

**Comment by steinjer** [comment]
I've the same problem. Using a group folder name with whitespace in name (e.g. "name with whitespace") will not sync with desktop client app.

Nexclound Server 16.0.5 
Group folders 4.1.4
Windows Desktop Client Version 2.6.1stable-Win64 (build 20191105)

**Comment by pierreozoux** [comment]
Do you still have the issue?

**Comment by cvbraeuer** [comment]
Disclaimer: My environment has changed. My server is running the latest Nextcloud 20.0.8. My desktop is running Manjaro with latest available Nextcloud Client 3.1.3 from official repositories.

My tests do not display any erratic behavior anymore. From my perspective, the issue is therefore resolved.
