### ISSUE TITLE
Deleting a file from a groupfolder copies the file to trashbin indefinitely

### ISSUE THREAD

**Issue by mjsaarin** [nextcloud/groupfolders#318]
Nextcloud: 15.0.4

When I have files_trashbin app enabled and I try to delete a file from a groupfolder Nextcloud begins copying the file to the trashbin and never stops. When we noticed this the first time we were on 15.0.2 and the deletion process managed to create 65000 copies of the deleted file to the trashbin bofore the web server stopped due to lack of disk space. Now, I tried the deletion with 15.0.4 and managed to stop the Apache and PHP when there were 100 copies of the deleted file.

Expected behaviour: only a single copy of the deleted file would be stored in the trashbin and the file should be removed from the original location.

**Comment by dirkpape** [comment]
this happens for me, too.

**Comment by GuidoDr** [comment]
same here, currently the only solution is to remove the NC15 encryption app (which is installed by default with every new NC15 release). For this I did remove the data/nextcloud/apps/encryption folder with all its files and did restart the nextcloud instance. (actually I did not really remove it, I moved it to data/**nextcloud-sav**/apps/encryption so that it is no longer used by NC but could be reinstalled).
But with every new NC15 release this step has to be done again. I just migrated from 15.0.4 to 15.0.5 and this reinstalled the encryption app, so I had to do the move again.

**Comment by mjsaarin** [comment]
> same here, currently the only solution is to remove the NC15 encryption app (which is installed by default with every new NC15 release). For this I did remove the data/nextcloud/apps/encryption folder with all its files and did restart the nextcloud instance. 

Unfortunately, that solution did not solve the problem in our case. We've never had encryption app enabled. Also, we removed the directory containing the app code but it had no effect. So, it seems the problem lies somewhere deeper. We are using S3 as primary storage which may or may not have any relation to this issue.

**Comment by icewind1991** [comment]
Can you check if 0dac7fcb5ca2d71544d2422c6b9a8a0086f51464 fixes the problem for you

**Comment by icewind1991** [comment]
Should be fixed with 2.0.4

**Comment by GuidoDr** [comment]
I can confirm, it is working fine at least on our instance with the encryption app enabled even though we do not use encryption. Thanks for the fix.

**Comment by dirkpape** [comment]
i can also confirm that the fix worked in my case (I implemented the patch). Thanks for the update.
