### ISSUE TITLE
Update of Group Folder app leads to resync on Desktop

### ISSUE THREAD

**Issue by anatomism** [nextcloud/groupfolders#37]
I use Group Folders (very useful by the way!) for all our files - everyone has NextCloud Desktop installed and syncs a total of 25GB (through many group folders) - last night I updated the app from the web GUI, and now everything is being re-pulled from the server to every computer.

25GB to 10 machines.... I'm hoping this is just a bug and won't happen every time I update the group folder app.

Thanks

**Comment by anatomism** [comment]
Any way to stop this would be appreciated... ETA for sync is 10 hours :\

Thanks

**Comment by anatomism** [comment]
Update - seemed to be linked to this: https://github.com/nextcloud/server/issues/5031 as all group folders where showing "Size Pending"

After `sudo -u www-data php occ files:scan --all` it 'fixed' the Size Pending issue and all files synced pretty rapidly (still apparently synced c. 20GB, but did it in 10 mins, as opposed to 5 hours.

**Comment by anatomism** [comment]
I'm still having problems.  I haven't applied fix #5708 or #5685 yet (will tonight) but the situation is now this:

Everyone can upload to group folder but not download anything (almost as if the desktop software does not detect changes).

All of my folders are "local" - they're actually NFS mounts, but done through Linux and should not be detectable by Nextcloud - oddly, one folder that is an NFS mount through Nextcloud still works...  Any ideas please?

**Comment by f8ttyc8t** [comment]
Same here - Raspberry PI + nextcloud 12. 
Pending file size.
Also, latest Windows client does not show file size of folder containing content with size > 2GB.

**Comment by anatomism** [comment]
Fix #5708 and #5685 did not work.  The only way I could get things working again was to downgrade to v1.0.2 of the app.

1) Disable and remove Group Folders
2) Download v1.0.2 and untarnished - move folder to apps folder and set permissions (to same as the other folders)
3) Enable app in web interface and do not allow the upgrade to v1.1.0 to happen
4) `occ files:scan --all` for good measure (may not be necessary)
5) Desktop software will redownload all files again
6) Sync is working again

There has to be an issue with v.1.1.0 as I've tried every alternative I can think of and it now seems I'm not the only one...

**Comment by pooh22** [comment]
I think I'm having the same issue, after updating nextcloud or the groupfolders app, the groupfolders app is automatically disabled (this is a problem for users!) and then when re-enabling it, the synchronisation is set to off on the client (also a problem). I think it all works well again after this step, but I find this hard to sell to the users.

I want to keep both nextcloud and groupfolders up to date, but I have to arrange for a special day and instructions for users to be able to do this. I can't keep along with all the bugfixes this way, because the users are no techies, but teachers of pre-teens (basisschool leraren in Dutch).

Is there a way to update without this happening, or is it a known bug?
