### ISSUE TITLE
Trash active though "Deleted Files" AddOn is disabled

### ISSUE THREAD

**Issue by Madic-** [nextcloud/groupfolders#464]
When deleting files from a group folder they are assigned to a trash bin, even though the AddOn "Deleted Files" is not enabled.
We have disabled this addon because files should be directly deleted.
The size of the folder __groupfolders/trash/* increases with every deleted file.

When "Deleted Files" is disabled, I would expect that a deleted file in a group folder also gets directly deleted.

Nextcloud Version: 15.0.7
Group Folders Version: 3.0.2

**Comment by Beeez** [comment]
I was wondering the same. The trash folder grows and grows without any way to properly purge the files out of it.

**Comment by hriekehof** [comment]
Hi,
i know there are always plenty of other important things to do, but the trashbin issues are adding up #455, #345, #314, #301 for example.
I it would be so great if something would be done here. @icewind1991 can you tell us something about the issues ? Most of the time the trashbin issues are not commented. Would be so nice to get some info on this topic

**Comment by Beeez** [comment]
Yeah the trash handling is atrocious. Users rarely manage their own trash already and we rely on trash retention on their personal files. With many group folders available things just keep piling up until we find out that storage is full because of tons of deleted items.

**Comment by landryb** [comment]
How do ppl manually cleanup in the meantime ? `rm -Rf __groupfolders/trash` && `delete from oc_filecache where path like '%__groupfolders/trash%'` ? Currently 160Gb & 260k files in there ....

**Comment by Beeez** [comment]
They probably aren't. I kind of just went in though and nuked it all though like you did. You could probably set up a cron job to run daily to delete trash that is older than X days - but that is a horrible band aid for something that should be native in Nextclouds trash handling.

**Comment by patricksebastien** [comment]
I have 365GB of trash, I just need a confirmation that it's safe to clean it manually:

- rm -Rf __groupfolders/trash
- delete from oc_filecache where path like '%__groupfolders/trash%'

Thanks

**Comment by cyBea** [comment]
I deletion didn't work anymore after executing the above commands because nextcloud moves to something like `__groupfolders/trash/1/`. I had to recreate this folder manually. So I suggest doing:

in file system: `rm -r __groupfolders/trash/*/*`
in database: `DELETE FROM oc_filecache WHERE PATH LIKE '%__groupfolders/trash%'`

seems to work for me

**Comment by expert-geeks** [comment]
Deleting all users trash was not an acceptable solution for me. I've written a bash script to delete files/folders from __groupfolders/trash/ older than a specified age. It also removes ~$lock_files .tmp. and .tmp files from trash as these seem pretty redundant as they're either corrupt or useless. References to trash are removed from oc_filecache table and then deleted from the fs. 

You may find that the find command returns 'too many arguments' and you'll want to change the find statement to use xargs or do it per __groupfolder/x/trash individually.. As always YMMV ;)

`#!/bin/bash
# User Values.
# Edit these to suit your server.
# ttr is 'time to retain', i.e. how long groupfolders trash should be retained.
# by default this is 7 days.
ttr=7
mysqluser=<nextcloud>
mysqlpass=<password>
nc_data_path=/path/to/your/nc_data

# Script.
deletedate=$( echo `date +'%s'` - $ttr*24*60*60|bc )

mysql -u $mysqluser -p$mysqlpass <<sqlcommands
USE nextcloud;
DELETE FROM oc_filecache WHERE path LIKE '%__groupfolders/trash/%' AND mtime <= $deletedate;
DELETE FROM oc_filecache WHERE path LIKE '%groupfolders/trash/%' AND name LIKE '~$%';
DELETE FROM oc_filecache WHERE path LIKE '%groupfolders/trash/%' AND name LIKE '%.tmp.%';
DELETE FROM oc_filecache WHERE path LIKE '%groupfolders/trash/%' AND name LIKE '%.tmp';
sqlcommands

find $nc_data_path/__groupfolders/trash/*/* -mtime +$ttr -delete
find $nc_data_path/__groupfolders/trash/*/* -name '~$*' -delete
find $nc_data_path/__groupfolders/trash/*/* -name '*.tmp.*' -delete
find $nc_data_path/__groupfolders/trash/*/* -name '*.tmp' -delete`

**Comment by feutl** [comment]
Would it also be a feasible solution to delete the files on the filesystem and run a `occ files:scan --all` or ` sudo -u www-data php occ files:scan --path=/user/files/my_groupfolder_path` like mentioned here https://github.com/nextcloud/groupfolders/issues/46 ?
Honestly I just hate to touch a database with so many valuable data by adding it manually and work around how NC is handling this.

What you think, until somebody gets the `trashbin_retention_obligation` also working for groupfolders.

**Comment by Beeez** [comment]
I am not very keen on manually doing this through the DB as well, seems very messy. I'm surprised that with multiple Issues reported about this, no one has picked this issue up.

**Comment by expert-geeks** [comment]
> Would it also be a feasible solution to delete the files on the filesystem and run a `occ files:scan --all` or ` sudo -u www-data php occ files:scan --path=/user/files/my_groupfolder_path` like mentioned here #46 ?

Not really, the trashbin is ignored when scanning afaik. The entries still exist in the database and will cause conflicts when you try to delete the file as the system thinks it's already been deleted.

> Honestly I just hate to touch a database with so many valuable data by adding it manually and work around how NC is handling this.

I agree, it's a huge oversight.

> What you think, until somebody gets the `trashbin_retention_obligation` also working for groupfolders.
> 
> I also played around with the `find` command and options like `mtime`, `atime` and `ctime` and all of the options do not show me the result I wanted. None of them knows when the files were deleted, based on the date shown in the WebUI trashbin. There are some files deleted on a certain date some 350 days ago, but I cannot filter them via the filesystem timestamps. This means, I end up deleting files which could have been deleted just some days ago, because of some older timestamps (creation, changed or accessed - last one is not trustworthy anyhow).
> 
> The script is great, but actually we would need the information from the DB and the deletion time, afterwards delete the file and update the DB.
That would be ideal.

> Also I am not sure how consistent, based on the above command, the process of deleting in DB and filesystem is. I must assume this runs out of sync earlier than later.

Well so far it appears to be a reasonable compromise and is working OK. If you want to purge the trash folders and database then amend the script to remove the date constraints and run it once a week/month on a Sunday morning. That would ensure things don't get out of sync.

**Comment by feutl** [comment]
> Well so far it appears to be a reasonable compromise and is working OK. If you want to purge the trash folders and database then amend the script to remove the date constraints and run it once a week/month on a Sunday morning. That would ensure things don't get out of sync.

Based on my findings and testings, I rather assume it runs out of sync quite easily. Especially if lots of files do get deleted from multiple users during the time period and if they are on the system for quite some time. I would not trust the filesystem timestamps to delete something from the DB and it would also be quite hard to find, I assume.

But thanks anyhow for the effort.

**Comment by mesiah1970-haydar** [comment]
> Deleting all users trash was not an acceptable solution for me. I've written a bash script to delete files/folders from __groupfolders/trash/ older than a specified age. Edit ttr, mysqluser, mysqlpass and nc_data_path variables to suit you. This script also removes all ~$lock_files .tmp. and .tmp files from trash, regardless of age, these seem pretty redundant as they're either corrupt or useless in my experience. References to trash are removed from oc_filecache table and then deleted from the fs.
> 
> You may discover that the find command returns 'too many arguments' and you'll want to change the find statement to use xargs (use something like: `find $nc_data_path/__groupfolders/trash/*/* -mtime +$ttr | xargs rm -Rf `) or do it per __groupfolder/x/trash individually..
> 
> This worked for me, but be aware there are no checks or balances running this script. In theory, only your groupfolders trash is at stake but as always YMMV ;)
> 
> EDIT: I've added sql commands to delete the files out of the oc_group_folders_trash too, as this was stopping files with the same name and path from being deleted once removed from the oc_filecache table.
> 
> ```
> #!/bin/bash
> #User Values.
> #Edit these to suit your server.
> #ttr is 'time to retain', i.e. how long groupfolders trash should be retained.
> #by default this is 7 days.
> ttr=7
> mysqluser=<nextcloud>
> mysqlpass=<password>
> nc_data_path=/path/to/your/nc_data
> 
> #Script.
> let deletedate=$((`date +'%s'`))-$(($ttr*24*60*60))
> 
> mysql -u $mysqluser -p$mysqlpass <<sqlcommands
> USE nextcloud;
> DELETE FROM oc_filecache WHERE path LIKE '%__groupfolders/trash/%' AND mtime <= $deletedate;
> DELETE FROM oc_group_folders_trash WHERE deleted_time <= $deletedate;
> DELETE FROM oc_filecache WHERE path LIKE '%groupfolders/trash/%' AND name LIKE '~$%';
> DELETE FROM oc_group_folders_trash WHERE name LIKE '~$%';
> DELETE FROM oc_filecache WHERE path LIKE '%groupfolders/trash/%' AND name LIKE '%.tmp.%';
> DELETE FROM oc_group_folders_trash WHERE name LIKE '%.tmp.%';
> DELETE FROM oc_filecache WHERE path LIKE '%groupfolders/trash/%' AND name LIKE '%.tmp';
> DELETE FROM oc_group_folders_trash WHERE name LIKE '%.tmp';
> sqlcommands
> 
> find $nc_data_path/__groupfolders/trash/*/* -mtime +$ttr -exec rm -rv {} \;
> find $nc_data_path/__groupfolders/trash/*/* -name '~$*' -delete
> find $nc_data_path/__groupfolders/trash/*/* -name '*.tmp.*' -delete
> find $nc_data_path/__groupfolders/trash/*/* -name '*.tmp' -delete
> ```

Hello,

great script. I have a postgres Database, ist there anything similiar like this for postscript? I'm not really a scripter:-(

Haydar

**Comment by mesiah1970-haydar** [comment]
Hello and Good morning,

yes I agree, the group folders trashbin should expire. Maybe we can achieve this with a extra option in the group folder app, or create a new group folder occ command. It could be something simple, which could help people to get out of the trashbin mess. Please help us!

Rgds

Haydar

**Comment by Beeez** [comment]
> Hello and Good morning,
> 
> yes I agree, the group folders trashbin should expire. Maybe we can achieve this with a extra option in the group folder app, or create a new group folder occ command. It could be something simple, which could help people to get out of the trashbin mess. Please help us!
> 
> Rgds
> 
> Haydar

Group Folders shouldnt need a separate setting for this. It should just obey whatever trash retention policy is already in place for normal files in users trash.

**Comment by mesiah1970-haydar** [comment]
> > Hello and Good morning,
> > yes I agree, the group folders trashbin should expire. Maybe we can achieve this with a extra option in the group folder app, or create a new group folder occ command. It could be something simple, which could help people to get out of the trashbin mess. Please help us!
> > Rgds
> > Haydar
> 
> Group Folders shouldnt need a separate setting for this. It should just obey whatever trash retention policy is already in place for normal files in users trash.

Yeah your right, but I'm still wondering, why they didn't take care on the first place

**Comment by feutl** [comment]
Lets just link the two tickets, basically talking about the same.

https://github.com/nextcloud/groupfolders/issues/345

**Comment by Greek64** [comment]
@feutl 
> basically talking about the same.

While I do agree for linking them, since both talk about bugs with the groupfolder tsashbin, they are indeed very different.

One talks about disabling the groupfolder trash, when the "normal" trash is disabled, and the other talks about how groupfolder trash should respect the retention policy like the "normal" trash does.
The third is just a which feature of a do-all button to "save" 2 extra clicks.

**Comment by feutl** [comment]
@Greek64 
you are right, I updated the wording.

**Comment by mesiah1970-haydar** [comment]
@rullzer @nickvergessen 

will be there an update regarding this trashbin issue. So when a file gets into the trashbin from the group folder, it should be deleted accoring to the config.php settings. At the moment this is not possible

**Comment by mesiah1970-haydar** [comment]
@rullzer @nickvergessen

2nd reminder, Thanks

**Comment by nickvergessen** [comment]
Im far from being an expert or maintainer of this app so I will unsubscribe again, as I'm currently very busy with other topics (Nextcloud Talk)

**Comment by mesiah1970-haydar** [comment]
Hallo

@rullzer @juliushaertl @icewind1991

nun in Deutsch. Habt Ihr keine Zeit um dieses Bug anzunehmen? Oder schlichtweg nerven wir Euch. Vermutlich beides. Wäre aber trotzdem gut zu wissen ob Ihr auf diesen Bug eingehen wollt oder nicht oder wenigstens sagen könnt wann? Ich finde und wahrscheinlich bin ich nicht allein, dass Ihr keine validen Antworten geben könnt oder wollt. Ja ich weiß, der schon wieder oder die schon wieder ... Aber das würde uns nicht echt helfen.

Bitte sagt doch einfach bescheid, ob Ihr überhaupt noch diesen Bug beseitigen "wollt". Somit brauch ich Euch nicht wieder zu nerven.

LG

Mesiah

**Comment by feutl** [comment]
@mesiah1970-haydar 
In my case, and because of the trash thing not being resolved, I was able to move away from the group folders and using a shared folder instead.

But I am going to stick around, because this should be resolved.
Seems it gets more common with "nextcloud" apps under the "nextcloud" hood that they do lack communication. Even if they would just say, not now, but later in the future ;)

**Comment by mesiah1970-haydar** [comment]
@feutl 

This is the problem on my N instance, I was a little late to test the GF, so it was published to already to the public and I cannot take it back anymore. So my opinion is , stick always to the nextcloud itself, never to the apps;-)

**Comment by feutl** [comment]
@mesiah1970-haydar 
this is true
and therefor I removed it, even though it took some work.
after the last 1,5 years, even with updates I ran into multiple issues with group folders, the trash bin thing, I realized quite late, was just the tip of the iceberg.

**Comment by mesiah1970-haydar** [comment]
Ok, maybe I should go the same way, you did;-) So for me Group folders are a mess, And I cannot suggest to anyone and anybody. Maybe I can find some way to move the files from the GF to the shared folders

**Comment by feutl** [comment]
Off Topic

> What I did, was creating the same folders I was using with groupfolders (but not sharing them). Some people even suggested to create a groupfolder user which is owner of alle group foldes and later shares them to the persons.
> Anyhow, create the same structure but with a different name. Copy over all files, disable the group folder, rename the shared folder to match the group folder and share them.
> For me this was seamless, and the end users haven't even noticed it (or did not tell me ;) )

**Comment by mesiah1970-haydar** [comment]
> Off Topic
> 
> > What I did, was creating the same folders I was using with groupfolders (but not sharing them). Some people even suggested to create a groupfolder user which is owner of alle group foldes and later shares them to the persons.
> > Anyhow, create the same structure but with a different name. Copy over all files, disable the group folder, rename the shared folder to match the group folder and share them.
> > For me this was seamless, and the end users haven't even noticed it (or did not tell me ;) )

Yeah, but I've created a groupfolder for each projects and added a group to it with one user. This group and user is the owner. So far so good. This should work, but the folder owners share their group folders with externals outside in the public and password protected. I guess, this would be the greatest problem. Since every owner has to re-share again and renew the password.

Haydar

**Comment by mesiah1970-haydar** [comment]
The worst thing is, that you cannot address the issues here at github or nextcloud without being kicked. I would express my comments about the issues in the Nextcloud public not to use it

**Comment by feutl** [comment]
> 
> 
> The worst thing is, that you cannot address the issues here at github or nextcloud without being kicked. I would express my comments about the issues in the Nextcloud public not to use it

I would not say "nextcloud" is going to kick someone, because some projects under the nextcloud umbrella are quite well handled and do have a good communication and issue culture. Wheres others are not that great in both things ;)

**Comment by mesiah1970-haydar** [comment]
Yeah, but NC is always suggest us to go to github to address issues. My first point of entry was NC not github. Further I've addressed this issue also on Version 19 RC 2, the only thing they've said was this answer:

"Hello Haydar,

you repeated your comment regarding groupfolders app and thrashbin.
Please report such things at GitHub or add your comment to existings issues."

So what I'm gonna do. They play ping, and the are reaaaaly good at it

**Comment by mesiah1970-haydar** [comment]
Hallo

@rullzer @juliushaertl @icewind1991

with all respect, this sucks boys

**Comment by rullzer** [comment]
@mesiah1970-haydar please watch your tone. I'd like to remind you of our code of conduct. 

Mentioning us all the time is a not going to have us look at the issue any faster. It might even have the opposite effect.

Since this seems to be such an important issue to you I assume you have a support contract. In that case please do reach out. We have limited time and as a result of this we usually first have to spend our time and resources on the things our customers run into.

Of course another solution is to submit a pull request to get it fixed.
As I already have a todo list that is way longer than I'd like I'm going to unsubscribe here again.

**Comment by mesiah1970-haydar** [comment]
Hello rullzer

I'm not sure what are you trying to say, but if you mean, that I'm trying point out your lack information regarding this issue, which hangs since a long time, than I will not "watch my tone".  Certainly some words are funny of mine. But I'm gonna do it like that, if nobody comes down from his throne and tells us, why he/she is not correcting this issue. If you don't respond to questions, even if your answers might not be satisfying for all others, that's ok. At least you answered and explained your point of view, why you cannot act against this problems. I'm sure we will fully understand.

Although, it's even most interesting of you, that you only act on a situation, if someone acts a bit harsh. I guess this is the most interesting behavior of yours.

But it's ok if you thing I should "watch my mouth" yeah go away and kick me out. This is what I meant with   "The worst thing is, that you cannot address the issues here at github or nextcloud without being kicked. I would express my comments about the issues in the Nextcloud public not to use it"

Thank you

**Comment by Larx** [comment]
If the handling of such an important issue is like that, wouldn't it be fair to remove "Group folders" from the list of "official" nextcloud apps? I came here because I ran out of space on my server without any clue why this happened. I trusted in using official nextcloud apps and using the settings you can do from the web interface. I had no idea that group folders simply accumulate their trash without any chance of getting rid of it without messing around with the database.

So my urgent appeal: Don't sell something like that as "official" app!

**Comment by mesiah1970-haydar** [comment]
Hello Larx,

I totally agree with you, I had similar posting regarding this issue. But my contribution to this topic was marked as disruptive content. I agree people should be warned before using this App.

Haydar

**Comment by expert-geeks** [comment]
Function to clear group folders trash has recently been added by rullzer & juliushaertl (thanks guys!)

sudo -u www-data php /var/www/nextcloud/occ groupfolders:trashbin:cleanup

**Comment by biva** [comment]
Hello, we're wondering to use groupfolders in production, and I'm afraid of this issue: is this bug still present? Any update? I appreciate the function to clear the trash mentioned by @expert-geeks but I guess it's not a sustainable way on the long term, is it?
Thanks!

**Comment by expert-geeks** [comment]
> Hello, we're wondering to use groupfolders in production, and I'm afraid of this issue: is this bug still present? Any update? I appreciate the function to clear the trash mentioned by @expert-geeks but I guess it's not a sustainable way on the long term, is it?
> Thanks!

Currently the trash in the group folders doesn't at present respect the 'trashbin_retention_obligation' setting, but I understand that's being [worked on](https://github.com/nextcloud/groupfolders/pull/991).. Fingers crossed it get addressed soon.

**Comment by fschrempf** [comment]
@mesiah1970-haydar As you didn't get any proper response (except for the one from rullzer) to your complaints (and rants) above, here is a reply from my point of view (I'm not a NC developer, only a volunteer helping out here and there).

First, you are completely right that getting no response on issues like this is frustrating and I know this frustration myself. Complaining about this fact is alright. Ideally there should be some response from a developer in any case in an acceptable amount of time, even if it's just "we can't do anything at the moment". Though the world (and this project) is far from ideality. Please see the issue #1215 for more details and discussions about this general topic, which is completely unrelated to this issue. If you have suggestions or feedback, feel free to join the discussion.

Second, what is totally unacceptable is part of the attitude you have expressed above. NC is in the first place a community project. **Nobody owes you anything**. What makes you think anyone has a responsibility in fixing the issues you want to see fixed?
On the other hand, the good thing about a community project is, that you can join and fix the problem yourself or pay someone to do it as rullzer already suggested.

> But my contribution to this topic was marked as disruptive content.

For a reason. This issue is a technical issue and the discussion should stay on that topic. Blaming people because you think they should act to your liking is considered disruptive.

> The worst thing is, that you cannot address the issues here at github or nextcloud without being kicked. I would express my comments about the issues in the Nextcloud public not to use it

This is not true. You can voice your opinion whenever you want, but you have to stick to some rules and think about if your own expectations and attitude are appropriate.

**Comment by fschrempf** [comment]
> If the handling of such an important issue is like that, wouldn't it be fair to remove "Group folders" from the list of "official" nextcloud apps?

Yes, this is indeed a problem. Considering the app as stable and have it "featured" as official app is (or was, some things got better and were fixed) questionable to say the least. Please see #1215 for more information about this topic. Feel free to join the discussion.

**Comment by fschrempf** [comment]
> If the handling of such an important issue is like that, wouldn't it be fair to remove "Group folders" from the list of "official" nextcloud apps?

Yes, this is indeed a problem. Considering the app as stable and have it "featured" as official app is (or was, some things got better and were fixed) questionable to say the least. Please see #1215 for more information about this topic. Feel free to join the discussion.

**Comment by fschrempf** [comment]
The main point of this issue seems to be the trashbin expiration for groupfolders. A solution for this has been implemented in #1759 which will probably be released with v12 of the groupfolders app and NC 24. It's currently not clear if this will also be backported to other stable releases.

Please give this approach a try and provide feedback via new issues if required. Thanks!

**Comment by fschrempf** [comment]
Quoting [1759#979245063](https://github.com/nextcloud/groupfolders/pull/1759#issuecomment-979245063): The solution in #1759 has been backported to NC23 and will be part of the next point release (next week).
