### ISSUE TITLE
Get full access to a User repository

### ISSUE THREAD

**Issue by RonaldMayerhofer** [nextcloud/groupfolders#525]
In our scenario we need to get full access to a user repository. Not a subfolder of a user.

**Project Leader (Need full Access to all Subusers)
     contractor 1
     contractor 2
     customer 1**

The problem with group folders is when contractor 1 has uploaded one file to his root folder the project leader cannot access them

**Comment by fschrempf** [comment]
@RonaldMayerhofer I'm not sure what you are trying to do and what the actual problem is. Can you please look at the documentation in the README and check if you can use the advanced permissions (ACL) feature for your use-case?

I will close this issue and would like to ask you to open a new one if you think there is an actual problem with the current release, thanks!
