### ISSUE TITLE
Group Folder + Collabora Online = Not working

### ISSUE THREAD

**Issue by TP75** [nextcloud/groupfolders#58]
created a group folder, created a file there with a user from that group, and could not edit and save it

see [rich documents #70](https://github.com/nextcloud/richdocuments/issues/70)

**Comment by lars-becker** [comment]
We have the same problem. I can reproduce it on two different machines both working with NC 13.0.1 und current groupfolder app current versions app and Collabora 3.1.

If you disable the version app everything works as expected.

### Steps to reproduce

1. enable groupfolders and versions app and collabora integration
1. create a groupfolder `groupfolder_test`.
1. create a user `testuser` which is in the same group as the sharing user, but not in the group that has access to the `groupfolder_test`.
2. create a subfolder `testfolder_within_groupfolder` in the `groupfolder_test`.
3. share `testfolder_within_groupfolder` with user `testuser`
4. create a file `testfile.odt` within `testfolder_within_groupfolder`, open the file and enter a few words. save the document.
4. open the document `testfile.odt` with user `testuser`, edit the document and try to save the document.
5. The error message appears (in the german localisation it's "Das Dokument kann nicht gespeichert werden. Prüfen Sie Ihre Berechtigungen oder kontaktieren Sie den Administrator des Speicherservers.").
6. disable versions app
7. editing works as expected.

### Server configuration
Is independent of server configuration and php version:
**Operating system**: Linux, in one Case Centos in the other Ubuntu Server LTS.
**Web server:** In one case Apache 2.4.18 with mod_php, in the other 2.4.6 with php-fpm.
**PHP version:** 7.0.27 in the other 5.6.11
**Nextcloud version:** both use NC 13.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:** The Ubuntu system with PHP 5.6 runs on an installation that was upgrade since OwnCloud 7. The other was upgraded since Nextcloud 12.0.0.

#### Nextcloud error log

<summary>Just on relevant line which seems to indicate a problem with the versions app:</summary>

<details>
```
{"reqId":"qvQhXkfjJrzooKrsw9SX","level":3,"time":"March 20, 2018 00:07:36","remoteAddr":"78.46.xx.xxx","user":"demonutzer","app":"PHP","method":"POST","url":"\/index.php\/apps\/richdocuments\/wopi\/files\/79504_ocsg43fow8xa\/contents?access_token=CW22fmpMIOK5QYCrWfivJL6ETXqnZYN5&access_token_ttl=0&permission=edit","message":"Call to a member function getId() on boolean at \/var\/www\/nextcloud\/apps\/files_versions\/lib\/Storage.php#184","userAgent":"LOOLWSD WOPI Agent 3.1.0","version":"13.0.1.1"}
```
</details>

**Comment by AlexMaj** [comment]
I have the exact same issue but it happens not only with groupfolder app but also with any ext storage (local or smb)
if the user whith whom you share file does not have the folder "mounted" for him he can't save.
see [https://github.com/nextcloud/richdocuments/issues/184](url)
The trick you mentionned work for me too (disable version app) didn't notice that before thanks.
Can you try with ext storage see if same behaviour happens?

**Comment by TP75** [comment]
**Group folders** and **Collabora Online** are working on NC 13 and NC 14.
These _App_ versions are currently available: 

- **groupfolders 2.0.2**
- **richdocuments 3.0.6** (Collabora Online)

I presume, one should migrate to PHP 7.0 or later and please [check the settings in the php.ini files](https://docs.nextcloud.com/server/14/admin_manual/installation/source_installation.html#prerequisites-for-manual-installation) accordingly.

IMHO this issue can be called closed.
I would ask other contributors to establish a new issue at their deliberation.

Thanks to the contributors, mainly @icewind1991, for developing this app. I highly appreciate your efforts and time put into a free and open source app.
