### ISSUE TITLE
Double  folders in some group folders

### ISSUE THREAD

**Issue by bodangren** [nextcloud/groupfolders#61]
I have one group folder that has

* the full path in one of the folder names
*  two of those same file paths for each folder
*  The paths point to the same file on the system

It generally looks like this:

  * /path/to/Folder 1
     * File 1
  * /path/to/Folder 1
     * File 1

More explicitly:

  * {Group Folder Name}/Subfolder/Folder 1
    * File 1
  * {Group Folder Name}/Subfolder/Folder 1
    * File 1

The exposed file paths are identical while browsing the tree. Through search, though, I can see that the file paths actually are not completely identical:

* {Group Folder Name}/Subfolder/Folder 1
* {Group Folder Name}/_groupfolders/17/Subfolder/Folder 1

This result appears only when searching outside the group folder.

I'm having OnlyOffice problems with this group, and I suspect the double reference is the reason.

Ideas? NC12 on Ubuntu 16.04 LAMP stack, SSL through Let's Encrypt, not reverse proxied.

**Comment by putt1ck** [comment]
For clarity:

this issue appears in the webui and/or in the underlying file system?

**Comment by bodangren** [comment]
Just in the webui.

**Comment by viking-frank** [comment]
I have the Same Problem in the WebUI.
Folders are shown twice with full folder path (Group_Folder/Subfolder/folder1).

Interesting if i checkout Details > sharing, the folder is displayed correctly and the duplicate disappeares. But it gets back to the duplicate state when leaving and comming back to that folder. 

Any new progress on this?

**Comment by Britz** [comment]
Any new progress on this?

I have a quite similar issue. Some folders show up twice in the web UI and clicking them leads to the exact same folder content. For me, group folders are involved but the change form group folders to normally shared folders really caused the problem.

## How the problem was created 
Since group folders seem to be not very stable, I copied the files to another account and removed the group folders (and also the disabled the plugin afterwords). Then I just named the folders as the group folders where named before and shared them to the same groups. In short, I just replaced the group folders by normal sharing with a extra account for the group files (more or less the old way of group folders). 

## The problem
After that, all second level subfolders inside this folders are shown twice in the web-ui. 
Lets assume we in the former group folder named *former_group_folder*
It generally looks like this:

* folder1
* folder2
* file 1
* file 2

everything looks ok, but in deeper subfolder levels e.g. inside *folder1* the UI shows:

+ `/former_group_folder/folder1/`subfolder1
+ `/former_group_folder/folder1/`subfolder1
+ `/former_group_folder/folder1/`subfolder2
+ `/former_group_folder/folder1/`subfolder2
+ file 1
+ file 2

For the double entries, the full path is shown in grey color and it only affect folders, files are only shown once (and without full path).

## The hypothesis
Cleaning the file cache via occ, rescan files via occ, completely deleting browser cache, nothing helped. 
Probably, it is an issue in the database, where some entry are not correctly cleaned up and eventually these artefacts are introduced by sync clients. I noticed, that for some accounts the former group folder are still shown as external drives inside the sync client settings panel. Not sure if the problem is related, just want to mention it. 

## Info
NextCloud version 13.0.4
Group folders app disabled

**Comment by terrar** [comment]
Same in my NC 13.0.4.

I renamed the Groupfolder and added another group and now all folders and files in it are shown double.
When deleting one of them the other also is gone.
Any hint to clear this issue?

**Comment by ZeikoFr** [comment]
hI @bodangren is this issue still present in nextcloud 19/20 ?

**Comment by fschrempf** [comment]
Can anyone confirm this issues is still present in the latest release? Given how old this issue is, I will mark this as stale and close it soon if nobody objects.

**Comment by fschrempf** [comment]
I'm closing this as stale. If someone is able to reproduce this, please open a new issue. Thanks!
