### ISSUE TITLE
All users can view any deleted file regardless of rights given to subfolders

### ISSUE THREAD

**Issue by tquest1** [nextcloud/groupfolders#610]
We have group folders for each department in our organisation. Each group folder has the respective department user group added with write/share/delete rights in the Group Folder settings.
Then sub-folders under the group folders have differing advanced permissions starting with deny read for the whole group & then adding other permissions for those that need them.

The problem that we have found and it is a potentially very damaging one for sensitive information is, anyone that has any rights for the original group folder can view ANY file that has been deleted in ANY sub folder whether they have read rights or not in the deleted files.
Is there anyway to prevent this or am I using the advanced permissions incorrectly?

**Comment by tquest1** [comment]
Related nextcloud forum post:

https://help.nextcloud.com/t/all-users-can-view-any-deleted-file-regardless-of-rights-given-to-subfolders/60619

**Comment by Shen** [comment]
No Labels? No Milestone? No Assignees? In my opinion, this is an important security & privacy problem that must be resolved immediately - in particular, as it is an official Nextcloud app. @juliushaertl @icewind1991 @rullzer

**Comment by rullzer** [comment]
@tquest1 @Shen please be sure to always notify nextcloud support if you have a subscription. There are a lot of issues to review and triage and only so many hours in a day. We will take a look at this but it will take some time I think.

**Comment by t-markmann** [comment]
I understand that this bug seems to be only relevant for a special (enterprise) usergroup, but for admins who want to promote open source software in their small company or to students this is an unpleasant surprise as well.
Unfortunately I do not have a support subscription yet. Can we accelerate a bugfix with a bounty on https://www.bountysource.com/teams/nextcloud ?

Looking for a hint at the database...

In oc_group_folders_acl.permission my user/group has a '0'.

The oc_group_folders_trash.folder_id the (actually secret file) has the id of the major groupfolder, not of the "secret" subfolder.

So a way to check for the permission of the subfolder could be: 
* check if I am in a group, that has a '0' in oc_group_folders_acl.permission --> take the FILEID
* look up the PATH of this FILEID in oc_filecache
* Does this PATH equal oc_group_folders_trash.original_location ; then do not display it!

This is quite complicated for my taste. May you already have something elegant in your API or some class, that could handle this?
May this bug be fixed quickly in the files_trashbin app in a class that checks the permissions of the files to be shown?

**Comment by jospoortvliet** [comment]
@t-markmann I'm afraid bounties are not really something that pays our salaries. Sorry, we'd love to be able to give everyone great service, even those who don't or can't pay but that sadly isn't possible.

**Comment by nursoda** [comment]
The same issue hit me today. I also think that it's a major issue. Because there is no obvious solution thus no obvioud bug, the current trashbin is designed like that, most probably not with group folders and ACLs in mind. So let's first discuss what other system do, what users may expect and what options we see for NC group folders:

**Implementations:**
- Desktop systems trash files to a bin only accessible to the logged-in user.
- In Windows File Service, typically there is no trash bin for shares, files are just discarded.
- Samba implements a .trash, but that's usually not readable to users.

**Expectations:**
- Consider a group folder ("share") with two (sub)"folders":
   - "work", readable to all users of that group) and "hidden"
   - "orga", readable to a few group members (in ACL that is, deny group, allow some users)
- an orga user is logged in, creates a new version of a file and deletes its old version

He/She might expect that the deleted file is visible to other "orga" members.
However, there is no such group or means for nextcloud to decide which users shall (not) see it.

**Options:**
To me, there are only two obvious options:
- either group folder files should be moved to the user's (private) trashbin
- or group folder files should be deleted to a special trashbin only accessible to (group) admins
