### ISSUE TITLE
Nextcloud 17 Update:  Declaration of OCA Fatal Error

### ISSUE THREAD

**Issue by benhartwich** [nextcloud/groupfolders#625]
Hi,

I´ve upgraded my nextcloud from latest version of 16 to 17 with Group Folders App and fully encrypted mode on. During the Web Update of the modules after the core upgrade succeeded I got the following:

`PHP Fatal error:  Declaration of OCA\GroupFolders\Versions\VersionsBackend::getVersionFile(OCP\IUser $user, OCP\Files\FileInfo $sourceFile, int $revision): OCP\Files\File must be compatible with OCA\Files_Versions\Versions\IVersionBackend::getVersionFile(OCP\IUser $user, OCP\Files\FileInfo $sourceFile, $revision): OCP\Files\File in /var/kunden/cloud-secure/httpdocs/nextcloud/apps/groupfolders/lib/Versions/VersionsBackend.php on line 38`

What can I do to solve it?

Environment:
- Debian 9
- Nginx, php 7.3

**Comment by LyR33x** [comment]
Got the same error over here!

**Comment by ArnisR** [comment]
If You have shell access, update second stage with via cli:

sudo -u www-data occ upgrade -vv

**Comment by jimjulian** [comment]
Note I also had to make "occ" executable:

`sudo chmod +x occ`

**Comment by maxolasersquad** [comment]
If you run `sudo -u www-data php occ upgrade -vv` then it's not necessary to make occ executable.

**Comment by buzanits** [comment]
In my opinion type declarations in PHP functions have only one use: To produce errors at annoyed users. This all would work like a charm without it. So we have an error now that exists since half a year and will probably never been fixed.

They use a language (PHP) which has the advantage of maximal flexibility and then they throw away this advantage by using type declarations and additionally produce loads of errors with that. Never use new language features just because they exist!

**Comment by fschrempf** [comment]
@buzanits Thanks for letting us know what you think about this.

> So we have an error now that exists since half a year and will probably never been fixed.

It looks like this was even fixed before this issue was raised and it was probably only released at a later point in time: https://github.com/nextcloud/groupfolders/commit/fa87c7164d01fa4732fcbbc4b498cb4b2926b42e.

And as this is a community project, you are always free to fix issues yourself and send a PR. Especially if the solution is as simple as in this case.

**Comment by JigmeDatse** [comment]
Thanks to this, I *think* I found a rapid solution.  I'm not sure if I did something which caused it to break.  But it looks like the fix here has worked for me.
