### ISSUE TITLE
"CSRF check failed" 

### ISSUE THREAD

**Issue by alexisrosano89** [nextcloud/groupfolders#63]
I get a "CSRF check failed", when I execute:

curl -H "Content-Type: application/x-www-form-urlencoded" -X GET http://arosano:arosano@localhost/nextcloud/index.php/apps/groupfolders/folders -H "OCS-APIRequest: true"

Regards.

**Comment by cthiel** [comment]
I'm seeing the same issue.

**Comment by icewind1991** [comment]
I can't reproduce this issue with either nc12 or 13

```
curl -H "Content-Type: application/x-www-form-urlencoded" -X GET "http://admin:admin@localhost:38465/index.php/apps/groupfolders/folders" -H "OCS-APIRequest: true"
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>```

**Comment by mamatt** [comment]
Nextcloud 12.0.4 , same issue
I get a "no app in context" error in nextcloud.log

Does it's not supposed to be a called with "v1.php" for an OCS  API ?

-> curl -sS -u ADMIN:XXXXXXX -H "OCS-APIRequest: true" -X GET http://mycloudserver/ocs/v1.php/app/groupfolders/folders

**Comment by icewind1991** [comment]
`example.com/index.php/apps/groupfolders/folders` is the correct endpoint, `index.php` can be droped if the server is configured for "pretty urls"

**Comment by alexisrosano89** [comment]
curl -H "Content-Type: application/x-www-form-urlencoded" -X GET "http://admin:admin@localhost/nextcloud/index.php/apps/groupfolders/folders" -H "OCS-APIRequest: true"

Not works for me

**Comment by alexisrosano89** [comment]
BTW,

How can create a folder and associate it to a group via OCS?

**Comment by icewind1991** [comment]
See https://github.com/nextcloud/groupfolders#api

**Comment by alexisrosano89** [comment]
`POST apps/groupfolders/folders`: Create a new group folder.
    `mountpoint`: The name for the new folder.

I dont know what it means with `mountpoint`

**Comment by gug9sch** [comment]
Same problem here.
I tried it with the full domain listed in 'trusted_domains' and on the server as 'localhost', but neither of them worked.

Is there a way to disable the CSRF check for certain IPs until the bug is fixed?

**Comment by alexisrosano89** [comment]
curl -X POST -H  "OCS-APIRequest:true" -v http://admin:admin@localhost/nextcloud/ocs/v1.php/apps/groupfolders/folders -d mountpoint:"AFJU"

This is not working for me.

**Comment by landryb** [comment]
I think the problem here (to my understanding) is that groupfolders doesnt use the same 'api base endpoint' as OCS API (ie the routes are not under `/ocs/v1.php`) and thus trigger the CSRF check. 

In my case here with `user_cas` & `user_ldap` enabled, calling the `/apps/groupfolders/folders` route with a basic auth header triggers a 302 to `/apps/user_cas/login`, while calling regular other APIs under `/ocs/v1.php` with the same auth header works with curl.

@icewind1991 does this make sense to you ? Shouldn't the groupfolder API routes be under `/ocs/v1.php` ? So far there's only the system `/ocs/v1.php/cloud/apps/groupfolders` route which gives app-level informations here, so maybe the routes defined in https://github.com/nextcloud/groupfolders/blob/master/js/Api.ts#L16 should be moved there ?

**Comment by landryb** [comment]
That's definitely the issue here - if i disable `cas_force_login` or set an exception for an ip via `cas_force_login_exceptions` the groupfolders API works fine from the given IP. So there's some kind of conflict here....

**Comment by landryb** [comment]
And digging more in `user_cas` code, this really hints that the groupfolders API calls should be under `/ocs` as `user_cas` whitelists this prefix (among others) and the module doesnt take the same codepaths (even if cas login is enforced), cf https://github.com/felixrupp/user_cas/blob/master/appinfo/app.php#L44

@icewind1991 - do you see other implications to this change ? is it feasible to move the API base ? Not sure since it seems declared in the typescript code and not the serverside php code.. but will try.

**Comment by egandro** [comment]
I can confirm - disabling LDAP will allow this to work.

**Comment by egandro** [comment]
Any progress on this?

**Comment by fschrempf** [comment]
Does anyone know if this issue is still present in the latest release?

**Comment by fschrempf** [comment]
I'm closing this as stale. Please open a new issue if this problem persists. Thanks!
