### ISSUE TITLE
Multiple times nested group folders break desktop sync

### ISSUE THREAD

**Issue by thoro** [nextcloud/groupfolders#652]
This issue is raised from #597

I have setup a testing instance now, but I have the same issue with 16.0.5 and 4.0.5. Possibly the issue is different from the other guys.

For me the local sync NEVER happens, even if I Force Sync. Only when I uncheck and recheck in the client it will sync.

It's a multiple times nested groupfolder, I assume this might be the issue. Nested in this context means that the sub-mountpoint is overwritten multiple times i.e.:

/Level1
/Level1/Level2
/Level1/Level2/Level3
/Level1/Level2/Level3/Level4
/Level1/Level2/Level3/Level4/Level5

Each level contains various different permissions.

It's 5x nested. With a group folder nested only 3x it works completely fine. (with GF 4.0.5)
And was not working either with the 3x nesting with GF 4.1.3

During testing I only had the relevant folders checked as to be synced

**Comment by janpekar** [comment]
The same issue for me (tried GF 4.1.5 with Nextcloud 16.x and GF 5.0.5 with Nextcloud 17.0.3).
This makes "nested groups" folders unusable with desktop client.

**Comment by Patrock** [comment]
on my system i have sync issues with groupfolders , too...

NC-Version: 24.0.5 (and previous 23.X)  -> running on docker(Compose)
Group folder version: 12.0.2
Desktopclient Version: 3.6.2 (Windows)

The problem:
1. create groupfolder for group with User A & B
2. add files to webui (A)
3. no sync for user A & B
4. force sync by client A&B -> files appear
6. add files to desktop folder for A
7. files are synced to server but not to User B
8. wait .. .wait ... wait. ... nothing 
9. force sync on B -> files appear

also on nested groupfolder setups, in one case (our working structure with nested group folders) even  a forced synced does not work...

there are no logs to this issue.

What always works: untick folder in client and retick -> everything in sync...

normal syncs (with shared and owned files) are working fine

is there something i could test further ? Someone with similar problems ?

Thx

**Comment by VVD** [comment]
I'm using FreeBSD on both desktop and server and have this issue too.
My scenario for reproduce:
1. Create groupfolder /Test1, then /Test1/Test2 and configure access.
2. Turn on in Nextcloud Desktop Client sync of the /Test1 and /Test1/Test2.
3. In Nextclod web interface create file /Test1/Test2/test.txt.
4. Check local storage connected via Nextcloud Desktop Client - no new file /Test1/Test2/test.txt.
5. In Nextclod web interface create file /Test1/test.txt.
6. Check local storage connected via Nextcloud Desktop Client - both files are here /Test1/Test2/test.txt and /Test1/test.txt.


My environment:
### Server configuration
Operating system: FreeBSD 13.2-p9 amd64
Web server: Apache 2.4.58
Database: PostgreSQL 15.5
PHP version: PHP 8.2.14
Nextcloud version: 27.1.5
Group folders version: 15.3.2
Updated from an older Nextcloud or fresh install: Update via web-based internal updater
Where did you install Nextcloud from: tar.gz from official source
Are you using external storage, if yes which one: no (local)
Are you using encryption: no
Are you using an external user-backend, if yes which one: IMAP4 via External user authentication 3.2.0
### Client configuration
Browser: Firefox 121.0, Nextcloud Desktop-Client 3.10.1, 3.11.0
Operating system: FreeBSD 13.2-p9 amd64

P.S. 4 years have already passed, but the bug is still here...

**Comment by provokateurin** [comment]
Related issue https://github.com/nextcloud/groupfolders/issues/1787 got fixed by https://github.com/nextcloud/server/pull/44279, so this can be closed as well.
