### ISSUE TITLE
group folder wont update

### ISSUE THREAD

**Issue by Terrox** [nextcloud/groupfolders#66]
It wont refresh contents, I have edited files outside nextcloud and it still shows old contents for weeks.
I have three group folder shares and they are all having the same issue.

**Comment by putt1ck** [comment]
How have you edited the files outside Nextcloud - do you mean you've changed the files directly? Or on a local copy that you believe should be syncing?

**Comment by Terrox** [comment]
Files were changed directly and Nextcloud doesn't know and never checks.

**Comment by sduensin** [comment]
I've noticed this as well.  Probably going to have to work around it with an External Storage source.

**Comment by sduensin** [comment]
FYI, doing an "occ files:scan --all" will fix it, but man, that takes some time.

**Comment by ZeikoFr** [comment]
> It wont refresh contents, I have edited files outside nextcloud and it still shows old contents for weeks.
> I have three group folder shares and they are all having the same issue.

Hi, 

Since this issue is 3 Yo i think it might be fixed now ?

**Comment by juliushaertl** [comment]
If files are changed on the filesystem there is no way nextcloud will detect this without running a manual file scan. There is also `occ groupfolders:scan` these days to only scan one group folder for example, but changing files outside of Nextcloud is not recommended nor supported officially.

**Comment by sduensin** [comment]
That's really sad to hear it's not supported.  It removes a HUGE use case for Nextcloud - allowing easy access to network shares without a VPN.

**Comment by putt1ck** [comment]
@sduensin that functionality exists by using the "external storage" feature. However the reality is remote working and legacy file shares don't mix; if someone downloads a file from NC to work on it, and then someone else opens it on the file share they are causing havoc. The trick is to migrate away from legacy file shares to something more flexible like NC (other collaborative workspaces exist).

**Comment by sduensin** [comment]
If that's REALLY the goal, then Nextcloud seriously needs better than WebDAV for exporting filesystems.  I'm just looking for access, mind you, not collaborative editing or anything fancy.  For example, one of our servers generates a ton of binary data and log files that people need access to.  Giving them access to the Linux box that generates them is not a realistic option.  With it mapped as external storage, it does what I want.  Most of the time.  There are still way too many instances where I get the "I can't find my file!" email because Nextcloud refuses to refresh the file listing.  :-(

**Comment by ZeikoFr** [comment]
@sduensin Do you have an enterprise license on your NC ? If so you might be able to open an enterprise ticket with the support and ask for help in this specific situation

**Comment by sduensin** [comment]
Not yet.  It's something we're seriously considering though.
