### ISSUE TITLE
Advanced Permissions not saved if subfolder name starts with #

### ISSUE THREAD

**Issue by annievoss** [nextcloud/groupfolders#661]
If the name of the subfolder starts with #  the settings for advanced permissions for that folder are not saved. Everytime the site is reloaded, the permission bar is gone for every previously selected group or user.

**Comment by wiswedel** [comment]
I reproduced the issue with

- Server 17.0.0 & Group Folders 5.0.4
- Server 16.0.5 & Group Folders 4.1.4

However, the permissions don't get _not_ saved, it's actually the parent folder that receives the permissions, instead of the #-folder that the permissions had been set on.

@annievoss Can you please confirm that on your side?

**Comment by annievoss** [comment]
Yes, I can confirm that. Another thing I have found out is that if you set the permissions to the folder without having the # at the beginning and rename it afterwards, the permissions stay there.
But then again when the # is in place, all new set permissions go to the parent folder.

**Comment by pierreozoux** [comment]
duplicate of https://github.com/nextcloud/groupfolders/issues/925
