### ISSUE TITLE
Group admins can delete users globally

### ISSUE THREAD

**Issue by enis45** [nextcloud/groupfolders#776]
Hello everybody. I have a question and a fear. I use version 16.0.8, the group admins are ONLY in the group admins and not on the server or as "normal" administrators.

I found that group administrators can delete members globally. Global means including data folder and database entries. They are ONLY group admins. Is this problem known?

**Comment by HigH-HawK** [comment]
NC 17.0.3

I can confirm that if the group admin is executing the "Delete User" method, it deleted the user completely from NC.

The weird thing is, the group admin can delete the user from the NC server but is unable to remove the user from the group because of an error message:

```
An error occured during the request. Unable to proceed.
Not viable to remove user from the last group you are SubAdmin of
```

There seems to be a little mix up in the permissions but there is no way to manage these permissions per default NC installation.

**Comment by n15c** [comment]
This issue isn't related to the groupfolders app. You should post this issue in the nextcloud repository.

**Comment by twity1337** [comment]
Since this issue was the first thing I found while googling for this problem, you'll find the major issue here:
https://github.com/nextcloud/server/issues/44293
