### ISSUE TITLE
Creating a groupfolder fails if using adBlocker

### ISSUE THREAD

**Issue by bertl58** [nextcloud/groupfolders#932]
Hi all,
when trying to create a groupfolder using Firefos 76.0.1 (which is to my knowledge the most recent one under Win 10 Pro), the folder would not be created after clicking the button to create. After the click, the screen quickly refreshes, but the created folder won't show up - there's also no trace in the file system 
When using Chrome Version 83.0.4103.61, this works just fine....

Anyway, thank's for the great work,
Christian

**Comment by bertl58** [comment]
sorry, forgot to mention: nextcloud version is 18.0.4, add-on version is 6.0.6

**Comment by fzieris** [comment]
Do you use an adblocker or something else that might interfere with the JavaScript on the page? If yes: Try adding your domain to the adblocker's whitelist. I also encounter the problem from time to time, and the adblocker is my best guess so far.

**Comment by bpcurse** [comment]
Probably a duplicate or at least very similar to #862

**Comment by Zocker1999NET** [comment]
I just tried to find out, what might cause this issue so either uBlock Origin or Nextcloud could release a bug fix, but this issue seems to be a weird one.

About my setup/tests:
- I worked with Firefox 84.0.2 (64-bit) on Debian Unstable (Linux 5.10.0-1-amd64) with uBlock Origin installed from Mozilla's Add-on Repository, version 1.32.4.
- Disabling and enabling uBlock Origin means disabling/enabling the add-on globally using `about:addons`, **not** just disabling uBlock Origin on this page, as I can confirm, this does not make any difference here.
- After disabling/enabling uBlock Origin, I always reloaded the page with the cache disabled in Firefox Developer Tools to ensure the page behaves correctly.

For creating a new group folder: Disabling uBlock Origin once and then reloading seems to fix this issue for the whole session. Meaning, you can re-enable uBlock Origin and reload the page again (even when disabling cache in Firefox's Developer Tools) and creating group folders now works perfect (I have not tested to configure them). So I ignored this issue for a moment as I found other issues still happening, where I was able to do more research.

About deleting a group folder: This still works or fails depending on if uBlock Origin was disabled or enabled respectively. I monitored the network requests the site is issuing using Firefox' Network tab (in the Developer Tools) and the JS console while trying to delete a group folder. In both cases, to delete a group folder, a `DELETE /apps/groupfolders/folders/<id>` will be sent to the server, I compared the request headers and they are except for the `requesttoken` header (which differs for each request) exactly the same, so uBlock Origin does not seem to strip something here. Both requests also contain no content or other additional (form) parameters. Without uBlock Origin, it works fine, but with, it fails with a `500 Internal Server Error` status code. This is the corresponding error I found in my logs (I removed some sensitive values using `***PRIVATE***`):

```
[index] Error: BadMethodCallException: path needs to be relative to the system wide data folder and point to a user specific file at <<closure>>

 0. /var/webservers/***PRIVATE***/nextcloud/lib/private/Encryption/Keys/Storage.php line 368
    OC\Encryption\Util->getUidAndFilename("/__groupfolders/5")
 1. /var/webservers/***PRIVATE***/nextcloud/lib/private/Encryption/Keys/Storage.php line 190
    OC\Encryption\Keys\Storage->getFileKeyDir("", "/__groupfolders/5")
 2. /var/webservers/***PRIVATE***/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php line 317
    OC\Encryption\Keys\Storage->deleteAllFileKeys("/__groupfolders/5")
 3. <<closure>>
    OC\Files\Storage\Wrapper\Encryption->rmdir("__groupfolders/5")
 4. /var/webservers/***PRIVATE***/nextcloud/apps/files_trashbin/lib/Storage.php line 183
    call_user_func([OC\Files\Storag ... "], "__groupfolders/5")
 5. /var/webservers/***PRIVATE***/nextcloud/apps/files_trashbin/lib/Storage.php line 118
    OCA\Files_Trashbin\Storage->doDelete("__groupfolders/5", "rmdir")
 6. /var/webservers/***PRIVATE***/nextcloud/lib/private/Files/View.php line 1167
    OCA\Files_Trashbin\Storage->rmdir("__groupfolders/5")
 7. /var/webservers/***PRIVATE***/nextcloud/lib/private/Files/View.php line 350
    OC\Files\View->basicOperation("rmdir", "/__groupfolders/5", ["delete"])
 8. /var/webservers/***PRIVATE***/nextcloud/lib/private/Files/Node/Folder.php line 402
    OC\Files\View->rmdir("/__groupfolders/5")
 9. /var/webservers/***PRIVATE***/nextcloud/apps/groupfolders/lib/Controller/FolderController.php line 92
    OC\Files\Node\Folder->delete()
10. /var/webservers/***PRIVATE***/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
    OCA\GroupFolders\Controller\FolderController->removeFolder(5)
11. /var/webservers/***PRIVATE***/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\GroupFolders ... {}, "removeFolder")
12. /var/webservers/***PRIVATE***/nextcloud/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\GroupFolders ... {}, "removeFolder")
13. /var/webservers/***PRIVATE***/nextcloud/lib/private/Route/Router.php line 308
    OC\AppFramework\App::main("OCA\\GroupFolde ... r", "removeFolder", OC\AppFramework\ ... {}, {action: null,id ... "})
14. /var/webservers/***PRIVATE***/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/groupfolders/folders/5")
15. /var/webservers/***PRIVATE***/nextcloud/index.php line 37
    OC::handleRequest()

DELETE /apps/groupfolders/folders/5
from 2a02:8071:***PRIVATE*** by ***PRIVATE*** at 2021-01-19T12:06:05+00:00
```

I did not found any clue on why the request failed with uBlock Origin enabled because I could not find any differences in both requests. Has someone of you maybe an idea or can explain what causes the 500?

**Comment by pierreozoux** [comment]
I think we need to gather more data points before investigating where it comes from.

I do have ublock origin, and I can create delete group folders..

I can't reproduce.

**Comment by pierreozoux** [comment]
I'll close in favor of https://github.com/nextcloud/groupfolders/issues/1295
